// generated by newgenasym  Wed Jan 22 18:59:05 2014


module led1_bicolor4p (a1, a2, c1, c2);
    inout a1;
    inout a2;
    inout c1;
    inout c2;


    initial
        begin
        end

endmodule
