-- generated by newgenasym Wed Jan 22 18:59:05 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LED1_BICOLOR4P is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	C1:        INOUT  STD_LOGIC;    
	C2:        INOUT  STD_LOGIC);
end LED1_BICOLOR4P;
