// generated by newgenasym  Fri Oct 05 15:58:47 2007


module rsmd0805 (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
