// generated by newgenasym  Thu Jun 18 16:06:36 2015


module \74avc1t45  (a, b, dir, gnd, vcca, vccb);
    output a;
    input b;
    input dir;
    input gnd;
    input vcca;
    input vccb;


    initial
        begin
        end

endmodule
