-- generated by newgenasym Thu Jun 18 16:06:36 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74avc1t45\ is
    port (    
	A:         OUT    STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	DIR:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCCA:      IN     STD_LOGIC;    
	VCCB:      IN     STD_LOGIC);
end \74avc1t45\;
