-- generated by newgenasym Sun May 29 16:39:47 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity LTC2991 is
    port (    
	ADR0:      IN     STD_LOGIC;    
	ADR1:      IN     STD_LOGIC;    
	ADR2:      IN     STD_LOGIC;    
	PWM:       IN     STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	V1:        IN     STD_LOGIC;    
	V2:        IN     STD_LOGIC;    
	V3:        IN     STD_LOGIC;    
	V4:        IN     STD_LOGIC;    
	V5:        IN     STD_LOGIC;    
	V6:        IN     STD_LOGIC;    
	V7:        IN     STD_LOGIC;    
	V8:        IN     STD_LOGIC);
end LTC2991;
