// generated by newgenasym  Tue Jan 28 10:01:11 2025


module ld3985 (bypass, gnd, vi, vinh, vo);
    inout bypass;
    input gnd;
    input vi;
    inout vinh;
    input vo;


    initial
        begin
        end

endmodule
