-- generated by newgenasym Wed Mar  8 11:13:26 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \02_ power\ is
    port (    
	FPGA_PG:   IN     std_logic;    
	POWER:     INOUT  std_logic_vector (5 DOWNTO 0));
end \02_ power\;
