-- generated by newgenasym Fri Jun 21 09:22:43 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \sf-0603fp015f-2\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end \sf-0603fp015f-2\;
