-- generated by newgenasym Fri May 04 13:37:51 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CON16P is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (15 DOWNTO 0));
end CON16P;
