-- generated by newgenasym Fri Feb 23 09:44:50 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \sf-0603s300-2\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end \sf-0603s300-2\;
