// generated by newgenasym  Tue Aug 06 19:10:06 2013


module sw4int (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
