-- generated by newgenasym Tue Aug 06 19:10:06 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SW4INT is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end SW4INT;
