`timescale 1ns/1ns

module top ();
// generated by  HDL Direct 17.4-2019 S031 (4044358) 7/23/2022
// on Sat Dec 31 17:29:55 2022
// from mtca_interface_board_reocc/TOP/sch_1

  wire  fpga_pg;
  wire [180:0] bp;
  wire [10:0] power;
  wire [29:0] sfp;
  wire [27:0] timing;

// begin instances 

  \02_#20power  page2_1p  (.fpga_pg(fpga_pg),
	.power(power[10:0]));

  \08_#20timing  page2_2p  (.bp(bp[180:0]),
	.sfp(sfp[29:0]),
	.timing(timing[27:0]));

  \03_#20sfp  page2_3p  (.sfp(sfp[29:0]));

  \05#20trenz#20te0712#20fpga#20module  page2_4p  (.bp(bp[180:0]),
	.fpga_pg(fpga_pg),
	.sfp(sfp[29:0]),
	.timing(timing[27:0]));

  \01_#20module#20management#20ctrl  page2_5p  (.bp(bp[180:0]),
	.fpga_pg(fpga_pg),
	.power(power[10:0]));

  \07_#20backplane#20interface  page2_6p  (.bp(bp[180:0]));

endmodule // top(sch_1) 
