-- generated by newgenasym Tue Mar 12 15:08:17 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity wurth_155060ys73200 is
    port (    
	A:         INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC);
end wurth_155060ys73200;
