// generated by newgenasym  Thu Sep 18 11:56:59 2003


module \74lvc07a  (a, y);
    parameter    size = 1;
    input [size-1:0] a;
    output [size-1:0] y;


    initial
        begin
        end

endmodule
