// generated by newgenasym  Fri Feb 23 09:47:50 2024


module sit5022 (endis, gnd, outn, outp, vdd);
    input endis;
    inout gnd;
    output outn;
    output outp;
    inout vdd;


    initial
        begin
        end

endmodule
