-- generated by newgenasym Fri Feb 23 09:47:50 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sit5022 is
    port (    
	ENDIS:     IN     STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	OUTN:      OUT    STD_LOGIC;    
	OUTP:      OUT    STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end sit5022;
