// generated by newgenasym  Tue Oct  6 17:27:50 2026


module sw_dpdt_cas220ta1 (common1, common2, nc1, nc2, no1, no2);
    inout common1;
    inout common2;
    inout nc1;
    inout nc2;
    inout no1;
    inout no2;


    initial
        begin
        end

endmodule
