-- generated by newgenasym Tue Oct  6 17:27:50 2026

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SW_DPDT_CAS220TA1 is
    port (    
	COMMON1:   INOUT  STD_LOGIC;    
	COMMON2:   INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NO1:       INOUT  STD_LOGIC;    
	NO2:       INOUT  STD_LOGIC);
end SW_DPDT_CAS220TA1;
