-- generated by newgenasym Mon Oct  5 16:25:57 2026

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity kingbright_kpa is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end kingbright_kpa;
