-- generated by newgenasym Wed Nov 07 11:15:04 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CON14P is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (13 DOWNTO 0));
end CON14P;
