// generated by newgenasym  Wed Jul  3 07:21:52 2024


module \05#20trenz#20te0712#20fpga#20module  (bp, clkgen_io, data_select_p2v5, direct_us_data_2_n,
        direct_us_data_2_p, fpga_pg, sfp, sfp_data_io);
    inout [180:0] bp;
    inout [10:0] clkgen_io;
    inout data_select_p2v5;
    inout direct_us_data_2_n;
    inout direct_us_data_2_p;
    output fpga_pg;
    inout [29:0] sfp;
    inout [11:0] sfp_data_io;


    initial
        begin
        end

endmodule
