// generated by newgenasym  Tue Jul  2 15:04:35 2024


module \05#20trenz#20te0712#20fpga#20module  (bp, clkgen_io, fpga_pg, sfp, sfp_data_io, trenzdata);
    inout [180:0] bp;
    inout [10:0] clkgen_io;
    output fpga_pg;
    inout [29:0] sfp;
    inout [11:0] sfp_data_io;
    inout [3:0] trenzdata;


    initial
        begin
        end

endmodule
