// generated by newgenasym  Fri Jan 27 12:42:51 2023


module \05#20trenz#20te0712#20fpga#20module  (bp, clkgen_io, fpga_pg, sfp, sfp_data_io);
    inout [180:0] bp;
    inout [10:0] clkgen_io;
    output fpga_pg;
    inout [29:0] sfp;
    inout [11:0] sfp_data_io;


    initial
        begin
        end

endmodule
