-- generated by newgenasym Wed Jul  3 07:21:52 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \05 trenz te0712 fpga module\ is
    port (    
	BP:        INOUT  std_logic_vector (180 DOWNTO 0);    
	CLKGEN_IO: INOUT  std_logic_vector (10 DOWNTO 0);    
	DATA_SELECT_P2V5: INOUT  std_logic;    
	DIRECT_US_DATA_2_N: INOUT  std_logic;    
	DIRECT_US_DATA_2_P: INOUT  std_logic;    
	FPGA_PG:   OUT    std_logic;    
	SFP:       INOUT  std_logic_vector (29 DOWNTO 0);    
	SFP_DATA_IO: INOUT  std_logic_vector (11 DOWNTO 0));
end \05 trenz te0712 fpga module\;
