`timescale 1ns/1ns

module \07_#20backplane#20interface  (bp );
// generated by  HDL Direct 17.4-2019 S031 (4044358) 7/23/2022
// on Sat Dec 31 17:29:51 2022
// from mtca_interface_board_reocc/07_ BACKPLANE INTERFACE/sch_1

  inout [180:0] bp;
  // global signal glbl.gnd;
  // global signal glbl.mp3v3;
  // global signal glbl.vp12;

  wire  \bp.amc_ga0 ;
  wire  \bp.amc_ga1 ;
  wire  \bp.amc_ga2 ;
  wire  \bp.amc_ipmb_scl ;
  wire  \bp.amc_ipmb_sda ;
  wire  \bp.amc_n-enable ;
  wire  \bp.amc_n-ps0 ;
  wire  \bp.amc_n-ps1 ;
  wire  \bp.data_in_n0 ;
  wire  \bp.data_in_n1 ;
  wire  \bp.data_in_n10 ;
  wire  \bp.data_in_n11 ;
  wire  \bp.data_in_n2 ;
  wire  \bp.data_in_n3 ;
  wire  \bp.data_in_n4 ;
  wire  \bp.data_in_n5 ;
  wire  \bp.data_in_n6 ;
  wire  \bp.data_in_n7 ;
  wire  \bp.data_in_n8 ;
  wire  \bp.data_in_n9 ;
  wire  \bp.data_in_p0 ;
  wire  \bp.data_in_p1 ;
  wire  \bp.data_in_p10 ;
  wire  \bp.data_in_p11 ;
  wire  \bp.data_in_p2 ;
  wire  \bp.data_in_p3 ;
  wire  \bp.data_in_p4 ;
  wire  \bp.data_in_p5 ;
  wire  \bp.data_in_p6 ;
  wire  \bp.data_in_p7 ;
  wire  \bp.data_in_p8 ;
  wire  \bp.data_in_p9 ;
  wire  \bp.data_out_n0 ;
  wire  \bp.data_out_n1 ;
  wire  \bp.data_out_n10 ;
  wire  \bp.data_out_n11 ;
  wire  \bp.data_out_n2 ;
  wire  \bp.data_out_n3 ;
  wire  \bp.data_out_n4 ;
  wire  \bp.data_out_n5 ;
  wire  \bp.data_out_n6 ;
  wire  \bp.data_out_n7 ;
  wire  \bp.data_out_n8 ;
  wire  \bp.data_out_n9 ;
  wire  \bp.data_out_p0 ;
  wire  \bp.data_out_p1 ;
  wire  \bp.data_out_p10 ;
  wire  \bp.data_out_p11 ;
  wire  \bp.data_out_p2 ;
  wire  \bp.data_out_p3 ;
  wire  \bp.data_out_p4 ;
  wire  \bp.data_out_p5 ;
  wire  \bp.data_out_p6 ;
  wire  \bp.data_out_p7 ;
  wire  \bp.data_out_p8 ;
  wire  \bp.data_out_p9 ;
  wire  \bp.fpga_gbe_rxn ;
  wire  \bp.fpga_gbe_rxp ;
  wire  \bp.fpga_gbe_txn ;
  wire  \bp.fpga_gbe_txp ;
  wire  \bp.pwr_on ;
  wire  \bp.ref_clk_n0 ;
  wire  \bp.ref_clk_n1 ;
  wire  \bp.ref_clk_n10 ;
  wire  \bp.ref_clk_n11 ;
  wire  \bp.ref_clk_n2 ;
  wire  \bp.ref_clk_n3 ;
  wire  \bp.ref_clk_n4 ;
  wire  \bp.ref_clk_n5 ;
  wire  \bp.ref_clk_n6 ;
  wire  \bp.ref_clk_n7 ;
  wire  \bp.ref_clk_n8 ;
  wire  \bp.ref_clk_n9 ;
  wire  \bp.ref_clk_p0 ;
  wire  \bp.ref_clk_p1 ;
  wire  \bp.ref_clk_p10 ;
  wire  \bp.ref_clk_p11 ;
  wire  \bp.ref_clk_p2 ;
  wire  \bp.ref_clk_p3 ;
  wire  \bp.ref_clk_p4 ;
  wire  \bp.ref_clk_p5 ;
  wire  \bp.ref_clk_p6 ;
  wire  \bp.ref_clk_p7 ;
  wire  \bp.ref_clk_p8 ;
  wire  \bp.ref_clk_p9 ;
  wire  \bp.tck ;
  wire  \bp.tdi ;
  wire  \bp.tdo ;
  wire  \bp.tms ;
  wire  n00467;
  wire  n00469;
  wire  n00471;
  wire  segment1;
  wire  segment2;
  wire  segment3;
  wire [2:0] \bp.amc_ga ;
  wire [1:0] \bp.amc_n-ps ;
  wire [11:0] \bp.data_in_n ;
  wire [11:0] \bp.data_in_p ;
  wire [11:0] \bp.data_out_n ;
  wire [11:0] \bp.data_out_p ;
  wire [11:0] \bp.ref_clk_n ;
  wire [11:0] \bp.ref_clk_p ;

  wire [180:0] page2_bp;
  wire  gnd;
  wire  page2_gnd;
  wire  page1_gnd;
  wire  mp3v3;
  wire  page2_mp3v3;
  wire  vp12;
  wire  page2_vp12;

  assign page2_bp[180:0] = bp[180:0];
  assign page2_bp[180:0] = bp[180:0];
  assign gnd = glbl.gnd;
  assign page2_gnd = gnd;
  assign page1_gnd = gnd;
  assign mp3v3 = glbl.mp3v3;
  assign page2_mp3v3 = mp3v3;
  assign vp12 = glbl.vp12;
  assign page2_vp12 = vp12;

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign vp12  = glbl.vp12;
  assign mp3v3  = glbl.mp3v3;

// begin instances 

  mch_connector2_alt2 page1_7p  (.\clk1-1+ (\bp.data_in_n1 ),
	.\clk1-1- (\bp.data_in_p1 ),
	.\clk1-2+ (\bp.data_in_n0 ),
	.\clk1-2- (\bp.data_in_p0 ),
	.\clk1-3+ (/* unconnected */),
	.\clk1-3- (/* unconnected */),
	.\clk1-4+ (/* unconnected */),
	.\clk1-4- (/* unconnected */),
	.\clk1-5+ (/* unconnected */),
	.\clk1-5- (/* unconnected */),
	.\clk1-6+ (/* unconnected */),
	.\clk1-6- (/* unconnected */),
	.\clk1-7+ (/* unconnected */),
	.\clk1-7- (/* unconnected */),
	.\clk1-8+ (/* unconnected */),
	.\clk1-8- (/* unconnected */),
	.\clk1-9+ (/* unconnected */),
	.\clk1-9- (/* unconnected */),
	.\clk1-10+ (/* unconnected */),
	.\clk1-10- (/* unconnected */),
	.\clk1-11+ (/* unconnected */),
	.\clk1-11- (/* unconnected */),
	.\clk1-12+ (/* unconnected */),
	.\clk1-12- (/* unconnected */),
	.\clk1_rx+ (\bp.data_out_n8 ),
	.\clk1_rx- (\bp.data_out_p8 ),
	.\clk1_tx+ (\bp.ref_clk_n8 ),
	.\clk1_tx- (\bp.ref_clk_p8 ),
	.\clk2-1+ (\bp.data_in_n7 ),
	.\clk2-1- (\bp.data_in_p7 ),
	.\clk2-2+ (\bp.data_in_n6 ),
	.\clk2-2- (\bp.data_in_p6 ),
	.\clk2-3+ (/* unconnected */),
	.\clk2-3- (/* unconnected */),
	.\clk2-4+ (/* unconnected */),
	.\clk2-4- (/* unconnected */),
	.\clk2-5+ (/* unconnected */),
	.\clk2-5- (/* unconnected */),
	.\clk2-6+ (/* unconnected */),
	.\clk2-6- (/* unconnected */),
	.\clk2-7+ (/* unconnected */),
	.\clk2-7- (/* unconnected */),
	.\clk2-8+ (/* unconnected */),
	.\clk2-8- (/* unconnected */),
	.\clk2-9+ (/* unconnected */),
	.\clk2-9- (/* unconnected */),
	.\clk2-10+ (/* unconnected */),
	.\clk2-10- (/* unconnected */),
	.\clk2-11+ (/* unconnected */),
	.\clk2-11- (/* unconnected */),
	.\clk2-12+ (/* unconnected */),
	.\clk2-12- (/* unconnected */),
	.\clk3-1+ (\bp.ref_clk_n1 ),
	.\clk3-1- (\bp.ref_clk_p1 ),
	.\clk3-2+ (\bp.ref_clk_n0 ),
	.\clk3-2- (\bp.ref_clk_p0 ),
	.\clk3-3+ (\bp.data_in_n5 ),
	.\clk3-3- (\bp.data_in_p5 ),
	.\clk3-4+ (\bp.data_in_n4 ),
	.\clk3-4- (\bp.data_in_p4 ),
	.\clk3-5+ (\bp.data_in_n3 ),
	.\clk3-5- (\bp.data_in_p3 ),
	.\clk3-6+ (\bp.data_in_n2 ),
	.\clk3-6- (\bp.data_in_p2 ),
	.\clk3-7+ (\bp.data_out_n1 ),
	.\clk3-7- (\bp.data_out_p1 ),
	.\clk3-8+ (\bp.data_out_n0 ),
	.\clk3-8- (\bp.data_out_p0 ),
	.\clk3-9+ (\bp.data_in_n11 ),
	.\clk3-9- (\bp.data_in_p11 ),
	.\clk3-10+ (\bp.data_in_n10 ),
	.\clk3-10- (\bp.data_in_p10 ),
	.\clk3-11+ (\bp.data_in_n9 ),
	.\clk3-11- (\bp.data_in_p9 ),
	.\clk3-12+ (\bp.data_in_n8 ),
	.\clk3-12- (\bp.data_in_p8 ),
	.\clk3_rx+ (\bp.data_out_n9 ),
	.\clk3_rx- (\bp.data_out_p9 ),
	.gnd1(gnd),
	.gnd2(gnd),
	.gnd3(gnd),
	.gnd4(gnd),
	.gnd5(gnd),
	.gnd6(gnd),
	.gnd7(gnd),
	.gnd8(gnd),
	.gnd9(gnd),
	.gnd10(gnd),
	.gnd11(gnd),
	.gnd12(gnd),
	.gnd13(gnd),
	.gnd14(gnd),
	.gnd15(gnd),
	.gnd16(gnd),
	.gnd17(gnd),
	.gnd18(gnd),
	.gnd19(gnd),
	.gnd20(gnd),
	.gnd21(gnd),
	.gnd22(gnd),
	.gnd23(gnd),
	.gnd24(gnd),
	.gnd25(gnd),
	.gnd26(gnd),
	.gnd27(gnd),
	.gnd28(gnd),
	.gnd29(gnd),
	.gnd30(gnd),
	.gnd31(gnd),
	.gnd32(gnd),
	.gnd33(gnd),
	.gnd34(gnd),
	.gnd35(gnd),
	.gnd36(gnd),
	.gnd37(gnd),
	.gnd38(gnd),
	.gnd39(gnd),
	.gnd40(gnd),
	.gnd41(gnd),
	.gnd42(gnd),
	.gnd43(gnd),
	.gnd44(gnd),
	.gnd45(gnd),
	.gnd46(gnd),
	.gnd47(gnd),
	.gnd48(gnd),
	.gnd49(gnd),
	.gnd50(gnd),
	.gnd51(gnd),
	.gnd52(gnd),
	.gnd53(gnd),
	.gnd54(gnd),
	.gnd55(gnd),
	.gnd56(gnd),
	.gnd57(gnd),
	.gnd58(gnd),
	.rsvd1(\bp.ref_clk_p10 ),
	.rsvd2(\bp.ref_clk_n10 ),
	.rsvd3(\bp.ref_clk_p11 ),
	.rsvd4(\bp.ref_clk_n11 ),
	.rsvd5(\bp.data_out_p10 ),
	.rsvd6(\bp.data_out_n10 ),
	.rsvd7(\bp.data_out_p11 ),
	.rsvd8(\bp.data_out_n11 ),
	.\rxfb-1+ (\bp.data_out_n7 ),
	.\rxfb-1- (\bp.data_out_p7 ),
	.\rxfb-2+ (\bp.data_out_n6 ),
	.\rxfb-2- (\bp.data_out_p6 ),
	.\rxfb-3+ (\bp.data_out_n5 ),
	.\rxfb-3- (\bp.data_out_p5 ),
	.\rxfb-4+ (\bp.data_out_n4 ),
	.\rxfb-4- (\bp.data_out_p4 ),
	.\rxfb-5+ (\bp.data_out_n3 ),
	.\rxfb-5- (\bp.data_out_p3 ),
	.\rxfb-6+ (\bp.data_out_n2 ),
	.\rxfb-6- (\bp.data_out_p2 ),
	.\txfb-1+ (\bp.ref_clk_n7 ),
	.\txfb-1- (\bp.ref_clk_p7 ),
	.\txfb-2+ (\bp.ref_clk_n6 ),
	.\txfb-2- (\bp.ref_clk_p6 ),
	.\txfb-3+ (\bp.ref_clk_n5 ),
	.\txfb-3- (\bp.ref_clk_p5 ),
	.\txfb-4+ (\bp.ref_clk_n4 ),
	.\txfb-4- (\bp.ref_clk_p4 ),
	.\txfb-5+ (\bp.ref_clk_n3 ),
	.\txfb-5- (\bp.ref_clk_p3 ),
	.\txfb-6+ (\bp.ref_clk_n2 ),
	.\txfb-6- (\bp.ref_clk_p2 ),
	.\txfub+ (\bp.ref_clk_n9 ),
	.\txfub- (\bp.ref_clk_p9 ));

  mt_hole page1_8p  (.mh_sig(gnd));

  \lshm-130-0xxx-l-dv-a-s  page1_9p  (.\1 (gnd),
	.\2 (gnd),
	.\3 (\bp.ref_clk_p0 ),
	.\4 (gnd),
	.\5 (\bp.ref_clk_n0 ),
	.\6 (gnd),
	.\7 (gnd),
	.\8 (\bp.ref_clk_p1 ),
	.\9 (gnd),
	.\10 (\bp.ref_clk_n1 ),
	.\11 (\bp.ref_clk_p2 ),
	.\12 (gnd),
	.\13 (\bp.ref_clk_n2 ),
	.\14 (gnd),
	.\15 (gnd),
	.\16 (\bp.ref_clk_p3 ),
	.\17 (gnd),
	.\18 (\bp.ref_clk_n3 ),
	.\19 (\bp.ref_clk_p4 ),
	.\20 (gnd),
	.\21 (\bp.ref_clk_n4 ),
	.\22 (gnd),
	.\23 (gnd),
	.\24 (\bp.ref_clk_p5 ),
	.\25 (gnd),
	.\26 (\bp.ref_clk_n5 ),
	.\27 (\bp.ref_clk_p6 ),
	.\28 (gnd),
	.\29 (\bp.ref_clk_n6 ),
	.\30 (gnd),
	.\31 (gnd),
	.\32 (\bp.ref_clk_p7 ),
	.\33 (gnd),
	.\34 (\bp.ref_clk_n7 ),
	.\35 (\bp.ref_clk_p8 ),
	.\36 (gnd),
	.\37 (\bp.ref_clk_n8 ),
	.\38 (gnd),
	.\39 (gnd),
	.\40 (\bp.ref_clk_p9 ),
	.\41 (gnd),
	.\42 (\bp.ref_clk_n9 ),
	.\43 (\bp.ref_clk_p10 ),
	.\44 (gnd),
	.\45 (\bp.ref_clk_n10 ),
	.\46 (gnd),
	.\47 (gnd),
	.\48 (\bp.ref_clk_p11 ),
	.\49 (gnd),
	.\50 (\bp.ref_clk_n11 ),
	.\51 (gnd),
	.\52 (gnd),
	.\53 (gnd),
	.\54 (gnd),
	.\55 (gnd),
	.\56 (gnd),
	.\57 (gnd),
	.\58 (gnd),
	.\59 (gnd),
	.\60 (gnd),
	.f1(gnd),
	.f2(gnd));

  mt_hole page1_10p  (.mh_sig(gnd));

  \lshm-150-0xxx-l-dv-a-s  page1_11p  (.\1 (gnd),
	.\2 (gnd),
	.\3 (\bp.data_in_p0 ),
	.\4 (gnd),
	.\5 (\bp.data_in_n0 ),
	.\6 (n00467),
	.\7 (gnd),
	.\8 (\bp.data_in_p1 ),
	.\9 (n00469),
	.\10 (\bp.data_in_n1 ),
	.\11 (\bp.data_in_p2 ),
	.\12 (gnd),
	.\13 (\bp.data_in_n2 ),
	.\14 (n00471),
	.\15 (gnd),
	.\16 (\bp.data_in_p3 ),
	.\17 (gnd),
	.\18 (\bp.data_in_n3 ),
	.\19 (\bp.data_in_p4 ),
	.\20 (gnd),
	.\21 (\bp.data_in_n4 ),
	.\22 (gnd),
	.\23 (gnd),
	.\24 (\bp.data_in_p5 ),
	.\25 (gnd),
	.\26 (\bp.data_in_n5 ),
	.\27 (\bp.data_in_p6 ),
	.\28 (gnd),
	.\29 (\bp.data_in_n6 ),
	.\30 (gnd),
	.\31 (gnd),
	.\32 (\bp.data_in_p7 ),
	.\33 (gnd),
	.\34 (\bp.data_in_n7 ),
	.\35 (\bp.data_in_p8 ),
	.\36 (gnd),
	.\37 (\bp.data_in_n8 ),
	.\38 (gnd),
	.\39 (gnd),
	.\40 (\bp.data_in_p9 ),
	.\41 (gnd),
	.\42 (\bp.data_in_n9 ),
	.\43 (\bp.data_in_p10 ),
	.\44 (gnd),
	.\45 (\bp.data_in_n10 ),
	.\46 (gnd),
	.\47 (gnd),
	.\48 (\bp.data_in_p11 ),
	.\49 (gnd),
	.\50 (\bp.data_in_n11 ),
	.\51 (\bp.data_out_p0 ),
	.\52 (gnd),
	.\53 (\bp.data_out_n0 ),
	.\54 (gnd),
	.\55 (gnd),
	.\56 (\bp.data_out_p1 ),
	.\57 (gnd),
	.\58 (\bp.data_out_n1 ),
	.\59 (\bp.data_out_p2 ),
	.\60 (gnd),
	.\61 (\bp.data_out_n2 ),
	.\62 (gnd),
	.\63 (gnd),
	.\64 (\bp.data_out_p3 ),
	.\65 (gnd),
	.\66 (\bp.data_out_n3 ),
	.\67 (\bp.data_out_p4 ),
	.\68 (gnd),
	.\69 (\bp.data_out_n4 ),
	.\70 (gnd),
	.\71 (gnd),
	.\72 (\bp.data_out_p5 ),
	.\73 (gnd),
	.\74 (\bp.data_out_n5 ),
	.\75 (\bp.data_out_p6 ),
	.\76 (gnd),
	.\77 (\bp.data_out_n6 ),
	.\78 (gnd),
	.\79 (gnd),
	.\80 (\bp.data_out_p7 ),
	.\81 (gnd),
	.\82 (\bp.data_out_n7 ),
	.\83 (\bp.data_out_p8 ),
	.\84 (gnd),
	.\85 (\bp.data_out_n8 ),
	.\86 (gnd),
	.\87 (gnd),
	.\88 (\bp.data_out_p9 ),
	.\89 (gnd),
	.\90 (\bp.data_out_n9 ),
	.\91 (\bp.data_out_p10 ),
	.\92 (gnd),
	.\93 (\bp.data_out_n10 ),
	.\94 (gnd),
	.\95 (gnd),
	.\96 (\bp.data_out_p11 ),
	.\97 (gnd),
	.\98 (\bp.data_out_n11 ),
	.\99 (gnd),
	.\100 (gnd),
	.f1(gnd),
	.f2(gnd));

  mt_hole page1_12p  (.mh_sig(gnd));

  mt_hole page1_13p  (.mh_sig(gnd));

  mt_hole page2_17p  (.mh_sig(gnd));

  mt_hole page2_18p  (.mh_sig(gnd));

  mch_connector1 page2_19p  (.\enable# (/* unconnected */),
	.ga0(\bp.amc_ga0 ),
	.ga1(\bp.amc_ga1 ),
	.ga2(\bp.amc_ga2 ),
	.gnd1(gnd),
	.gnd2(gnd),
	.gnd3(gnd),
	.gnd4(gnd),
	.gnd5(gnd),
	.gnd6(gnd),
	.gnd7(gnd),
	.gnd8(gnd),
	.gnd9(gnd),
	.gnd10(gnd),
	.gnd11(gnd),
	.gnd12(gnd),
	.gnd13(gnd),
	.gnd14(gnd),
	.gnd15(gnd),
	.gnd16(gnd),
	.gnd17(gnd),
	.gnd18(gnd),
	.gnd19(gnd),
	.gnd20(gnd),
	.gnd21(gnd),
	.gnd22(gnd),
	.gnd23(gnd),
	.gnd24(gnd),
	.gnd25(gnd),
	.gnd26(gnd),
	.gnd27(gnd),
	.gnd28(gnd),
	.gnd29(gnd),
	.gnd30(gnd),
	.gnd31(gnd),
	.gnd32(gnd),
	.gnd33(gnd),
	.gnd34(gnd),
	.gnd35(gnd),
	.gnd36(gnd),
	.gnd37(gnd),
	.gnd38(gnd),
	.gnd39(gnd),
	.gnd40(gnd),
	.gnd41(gnd),
	.gnd42(gnd),
	.gnd43(gnd),
	.gnd44(gnd),
	.gnd45(gnd),
	.gnd46(gnd),
	.gnd47(gnd),
	.gnd48(gnd),
	.gnd49(gnd),
	.gnd50(gnd),
	.gnd51(gnd),
	.gnd52(gnd),
	.gnd53(gnd),
	.gnd54(gnd),
	.gnd55(gnd),
	.i2c_scl(/* unconnected */),
	.i2c_sda(/* unconnected */),
	.\ipmb0-scl-a (/* unconnected */),
	.\ipmb0-scl-b (/* unconnected */),
	.\ipmb0-sda-a (/* unconnected */),
	.\ipmb0-sda-b (/* unconnected */),
	.\ipmbl-scl-1 (/* unconnected */),
	.\ipmbl-scl-2 (/* unconnected */),
	.\ipmbl-scl-3 (/* unconnected */),
	.\ipmbl-scl-4 (/* unconnected */),
	.\ipmbl-scl-5 (/* unconnected */),
	.\ipmbl-scl-6 (/* unconnected */),
	.\ipmbl-scl-7 (/* unconnected */),
	.\ipmbl-scl-8 (/* unconnected */),
	.\ipmbl-scl-9 (/* unconnected */),
	.\ipmbl-scl-10 (/* unconnected */),
	.\ipmbl-scl-11 (/* unconnected */),
	.\ipmbl-scl-12 (/* unconnected */),
	.\ipmbl-sda-1 (/* unconnected */),
	.\ipmbl-sda-2 (/* unconnected */),
	.\ipmbl-sda-3 (/* unconnected */),
	.\ipmbl-sda-4 (/* unconnected */),
	.\ipmbl-sda-5 (/* unconnected */),
	.\ipmbl-sda-6 (/* unconnected */),
	.\ipmbl-sda-7 (/* unconnected */),
	.\ipmbl-sda-8 (/* unconnected */),
	.\ipmbl-sda-9 (/* unconnected */),
	.\ipmbl-sda-10 (/* unconnected */),
	.\ipmbl-sda-11 (/* unconnected */),
	.\ipmbl-sda-12 (/* unconnected */),
	.mp(mp3v3),
	.\ps0# (\bp.amc_n-ps0 ),
	.\ps1# (\bp.amc_n-ps1 ),
	.pwr1(vp12),
	.pwr2(vp12),
	.pwr3(vp12),
	.pwr4(vp12),
	.pwr5(vp12),
	.pwr6(vp12),
	.pwr7(vp12),
	.pwr8(vp12),
	.pwr_on(\bp.pwr_on ),
	.rsvd(/* unconnected */),
	.rsvd0(/* unconnected */),
	.rsvd1(/* unconnected */),
	.\rxfa-1+ (/* unconnected */),
	.\rxfa-1- (/* unconnected */),
	.\rxfa-2+ (/* unconnected */),
	.\rxfa-2- (/* unconnected */),
	.\rxfa-3+ (/* unconnected */),
	.\rxfa-3- (/* unconnected */),
	.\rxfa-4+ (/* unconnected */),
	.\rxfa-4- (/* unconnected */),
	.\rxfa-5+ (/* unconnected */),
	.\rxfa-5- (/* unconnected */),
	.\rxfa-6+ (/* unconnected */),
	.\rxfa-6- (/* unconnected */),
	.\rxfa-7+ (/* unconnected */),
	.\rxfa-7- (/* unconnected */),
	.\rxfa-8+ (/* unconnected */),
	.\rxfa-8- (/* unconnected */),
	.\rxfa-9+ (/* unconnected */),
	.\rxfa-9- (/* unconnected */),
	.\rxfa-10+ (/* unconnected */),
	.\rxfa-10- (/* unconnected */),
	.\rxfa-11+ (/* unconnected */),
	.\rxfa-11- (/* unconnected */),
	.\rxfa-12+ (/* unconnected */),
	.\rxfa-12- (/* unconnected */),
	.\rxfua+ (\bp.fpga_gbe_rxp ),
	.\rxfua- (\bp.fpga_gbe_rxn ),
	.scl_l(\bp.amc_ipmb_scl ),
	.sda_l(\bp.amc_ipmb_sda ),
	.tck(\bp.tck ),
	.tdi(\bp.tdi ),
	.tdo(\bp.tdo ),
	.\tmreq# (/* unconnected */),
	.tms(\bp.tms ),
	.\trst# (/* unconnected */),
	.\txfa-1+ (/* unconnected */),
	.\txfa-1- (/* unconnected */),
	.\txfa-2+ (/* unconnected */),
	.\txfa-2- (/* unconnected */),
	.\txfa-3+ (/* unconnected */),
	.\txfa-3- (/* unconnected */),
	.\txfa-4+ (/* unconnected */),
	.\txfa-4- (/* unconnected */),
	.\txfa-5+ (/* unconnected */),
	.\txfa-5- (/* unconnected */),
	.\txfa-6+ (/* unconnected */),
	.\txfa-6- (/* unconnected */),
	.\txfa-7+ (/* unconnected */),
	.\txfa-7- (/* unconnected */),
	.\txfa-8+ (/* unconnected */),
	.\txfa-8- (/* unconnected */),
	.\txfa-9+ (/* unconnected */),
	.\txfa-9- (/* unconnected */),
	.\txfa-10+ (/* unconnected */),
	.\txfa-10- (/* unconnected */),
	.\txfa-11+ (/* unconnected */),
	.\txfa-11- (/* unconnected */),
	.\txfa-12+ (/* unconnected */),
	.\txfa-12- (/* unconnected */),
	.\txfua+ (\bp.fpga_gbe_txp ),
	.\txfua- (\bp.fpga_gbe_txn ),
	.\xover0+ (/* unconnected */),
	.\xover0- (/* unconnected */),
	.\xover1+ (/* unconnected */),
	.\xover1- (/* unconnected */),
	.\xover2+ (/* unconnected */),
	.\xover2- (/* unconnected */));

  r page2_20p  (.\1 (\bp.pwr_on ),
	.\2 (gnd));

  mt_hole page2_21p  (.mh_sig(segment3));

  mt_hole page2_22p  (.mh_sig(gnd));

  mt_hole page2_23p  (.mh_sig(/* unconnected */));

  r page2_24p  (.\1 (segment2),
	.\2 (gnd));

  \lshm-130-0xxx-l-dv-a-s  page2_25p  (.\1 (gnd),
	.\2 (gnd),
	.\3 (gnd),
	.\4 (\bp.ref_clk_p0 ),
	.\5 (gnd),
	.\6 (\bp.ref_clk_n0 ),
	.\7 (\bp.ref_clk_p1 ),
	.\8 (gnd),
	.\9 (\bp.ref_clk_n1 ),
	.\10 (gnd),
	.\11 (gnd),
	.\12 (\bp.ref_clk_p2 ),
	.\13 (gnd),
	.\14 (\bp.ref_clk_n2 ),
	.\15 (\bp.ref_clk_p3 ),
	.\16 (gnd),
	.\17 (\bp.ref_clk_n3 ),
	.\18 (gnd),
	.\19 (gnd),
	.\20 (\bp.ref_clk_p4 ),
	.\21 (gnd),
	.\22 (\bp.ref_clk_n4 ),
	.\23 (\bp.ref_clk_p5 ),
	.\24 (gnd),
	.\25 (\bp.ref_clk_n5 ),
	.\26 (gnd),
	.\27 (gnd),
	.\28 (\bp.ref_clk_p6 ),
	.\29 (gnd),
	.\30 (\bp.ref_clk_n6 ),
	.\31 (\bp.ref_clk_p7 ),
	.\32 (gnd),
	.\33 (\bp.ref_clk_n7 ),
	.\34 (gnd),
	.\35 (gnd),
	.\36 (\bp.ref_clk_p8 ),
	.\37 (gnd),
	.\38 (\bp.ref_clk_n8 ),
	.\39 (\bp.ref_clk_p9 ),
	.\40 (gnd),
	.\41 (\bp.ref_clk_n9 ),
	.\42 (gnd),
	.\43 (gnd),
	.\44 (\bp.ref_clk_p10 ),
	.\45 (gnd),
	.\46 (\bp.ref_clk_n10 ),
	.\47 (\bp.ref_clk_p11 ),
	.\48 (gnd),
	.\49 (\bp.ref_clk_n11 ),
	.\50 (gnd),
	.\51 (gnd),
	.\52 (gnd),
	.\53 (gnd),
	.\54 (gnd),
	.\55 (gnd),
	.\56 (gnd),
	.\57 (gnd),
	.\58 (gnd),
	.\59 (gnd),
	.\60 (gnd),
	.f1(gnd),
	.f2(gnd));

  r page2_26p  (.\1 (segment1),
	.\2 (segment3));

  \lshm-150-0xxx-l-dv-a-s  page2_27p  (.\1 (gnd),
	.\2 (gnd),
	.\3 (gnd),
	.\4 (\bp.data_in_p0 ),
	.\5 (gnd),
	.\6 (\bp.data_in_n0 ),
	.\7 (\bp.data_in_p1 ),
	.\8 (gnd),
	.\9 (\bp.data_in_n1 ),
	.\10 (gnd),
	.\11 (gnd),
	.\12 (\bp.data_in_p2 ),
	.\13 (gnd),
	.\14 (\bp.data_in_n2 ),
	.\15 (\bp.data_in_p3 ),
	.\16 (gnd),
	.\17 (\bp.data_in_n3 ),
	.\18 (gnd),
	.\19 (gnd),
	.\20 (\bp.data_in_p4 ),
	.\21 (gnd),
	.\22 (\bp.data_in_n4 ),
	.\23 (\bp.data_in_p5 ),
	.\24 (gnd),
	.\25 (\bp.data_in_n5 ),
	.\26 (gnd),
	.\27 (gnd),
	.\28 (\bp.data_in_p6 ),
	.\29 (gnd),
	.\30 (\bp.data_in_n6 ),
	.\31 (\bp.data_in_p7 ),
	.\32 (gnd),
	.\33 (\bp.data_in_n7 ),
	.\34 (gnd),
	.\35 (gnd),
	.\36 (\bp.data_in_p8 ),
	.\37 (gnd),
	.\38 (\bp.data_in_n8 ),
	.\39 (\bp.data_in_p9 ),
	.\40 (gnd),
	.\41 (\bp.data_in_n9 ),
	.\42 (gnd),
	.\43 (gnd),
	.\44 (\bp.data_in_p10 ),
	.\45 (gnd),
	.\46 (\bp.data_in_n10 ),
	.\47 (\bp.data_in_p11 ),
	.\48 (gnd),
	.\49 (\bp.data_in_n11 ),
	.\50 (gnd),
	.\51 (gnd),
	.\52 (\bp.data_out_p0 ),
	.\53 (gnd),
	.\54 (\bp.data_out_n0 ),
	.\55 (\bp.data_out_p1 ),
	.\56 (gnd),
	.\57 (\bp.data_out_n1 ),
	.\58 (gnd),
	.\59 (gnd),
	.\60 (\bp.data_out_p2 ),
	.\61 (gnd),
	.\62 (\bp.data_out_n2 ),
	.\63 (\bp.data_out_p3 ),
	.\64 (gnd),
	.\65 (\bp.data_out_n3 ),
	.\66 (gnd),
	.\67 (gnd),
	.\68 (\bp.data_out_p4 ),
	.\69 (gnd),
	.\70 (\bp.data_out_n4 ),
	.\71 (\bp.data_out_p5 ),
	.\72 (gnd),
	.\73 (\bp.data_out_n5 ),
	.\74 (gnd),
	.\75 (gnd),
	.\76 (\bp.data_out_p6 ),
	.\77 (gnd),
	.\78 (\bp.data_out_n6 ),
	.\79 (\bp.data_out_p7 ),
	.\80 (gnd),
	.\81 (\bp.data_out_n7 ),
	.\82 (gnd),
	.\83 (gnd),
	.\84 (\bp.data_out_p8 ),
	.\85 (gnd),
	.\86 (\bp.data_out_n8 ),
	.\87 (\bp.data_out_p9 ),
	.\88 (gnd),
	.\89 (\bp.data_out_n9 ),
	.\90 (gnd),
	.\91 (gnd),
	.\92 (\bp.data_out_p10 ),
	.\93 (gnd),
	.\94 (\bp.data_out_n10 ),
	.\95 (\bp.data_out_p11 ),
	.\96 (gnd),
	.\97 (\bp.data_out_n11 ),
	.\98 (gnd),
	.\99 (gnd),
	.\100 (gnd),
	.f1(gnd),
	.f2(gnd));

  mt_hole page2_28p  (.mh_sig(gnd));

endmodule // \07_#20backplane#20interface (sch_1) 
