-- generated by newgenasym Thu Dec 01 08:47:05 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CON4P is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (3 DOWNTO 0));
end CON4P;
