-- generated by newgenasym Mon Jul 27 17:02:37 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dsc1123ci5 is
    port (    
	EN:        IN     STD_LOGIC;    
	OUTN:      OUT    STD_LOGIC;    
	OUTP:      OUT    STD_LOGIC);
end dsc1123ci5;
