// generated by newgenasym  Mon Jun 27 10:26:31 2022


module max9381esa (clk, \clk* , d, \d* , q, \q* , vcc, vee);
    input clk;
    input \clk* ;
    input d;
    input \d* ;
    output q;
    output \q* ;
    input vcc;
    input vee;


    initial
        begin
        end

endmodule
