-- generated by newgenasym Mon Jun 27 10:26:31 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max9381esa is
    port (    
	CLK:       IN     STD_LOGIC;    
	\clk*\:    IN     STD_LOGIC;    
	D:         IN     STD_LOGIC;    
	\d*\:      IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC;    
	\q*\:      OUT    STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end max9381esa;
