// generated by newgenasym  Thu Jul  3 10:38:38 2003


module header2x1 (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
