-- generated by newgenasym Thu Jul  3 10:38:38 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity HEADER2X1 is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end HEADER2X1;
