`timescale 1ns/1ns

module \03_#20sfp  (sfp );
// generated by  HDL Direct 17.4-2019 S031 (4044358) 7/23/2022
// on Sat Dec 31 17:29:54 2022
// from mtca_interface_board_reocc/03_ SFP/sch_1

  inout [29:0] sfp;

  wire  \sfp.los0 ;
  wire  \sfp.los1 ;
  wire  \sfp.los2 ;
  wire  \sfp.rate_select0 ;
  wire  \sfp.rate_select1 ;
  wire  \sfp.rate_select2 ;
  wire  \sfp.rd_n0 ;
  wire  \sfp.rd_n1 ;
  wire  \sfp.rd_n2 ;
  wire  \sfp.rd_p0 ;
  wire  \sfp.rd_p1 ;
  wire  \sfp.rd_p2 ;
  wire  \sfp.scl0 ;
  wire  \sfp.scl1 ;
  wire  \sfp.scl2 ;
  wire  \sfp.sda0 ;
  wire  \sfp.sda1 ;
  wire  \sfp.sda2 ;
  wire  \sfp.td_n0 ;
  wire  \sfp.td_n1 ;
  wire  \sfp.td_n2 ;
  wire  \sfp.td_p0 ;
  wire  \sfp.td_p1 ;
  wire  \sfp.td_p2 ;
  wire  \sfp.tx_disable0 ;
  wire  \sfp.tx_disable1 ;
  wire  \sfp.tx_disable2 ;
  wire  \sfp.tx_fault0 ;
  wire  \sfp.tx_fault1 ;
  wire  \sfp.tx_fault2 ;
  wire [2:0] \sfp.los ;
  wire [2:0] \sfp.rate_select ;
  wire [2:0] \sfp.rd_n ;
  wire [2:0] \sfp.rd_p ;
  wire [2:0] \sfp.scl ;
  wire [2:0] \sfp.sda ;
  wire [2:0] \sfp.td_n ;
  wire [2:0] \sfp.td_p ;
  wire [2:0] \sfp.tx_disable ;
  wire [2:0] \sfp.tx_fault ;

  wire [29:0] page1_sfp;

  assign page1_sfp[29:0] = sfp[29:0];
  assign page1_sfp[29:0] = sfp[29:0];

// begin instances 

  \04_#20sfp_module  page1_2p  (.los(\sfp.los0 ),
	.rate_select(\sfp.rate_select0 ),
	.rd_n(/* unconnected */),
	.rd_p(\sfp.rd_p0 ),
	.scl(\sfp.scl0 ),
	.sda(\sfp.sda0 ),
	.td_n(/* unconnected */),
	.td_p(/* unconnected */),
	.tx_disable(\sfp.tx_disable0 ),
	.tx_fault(\sfp.tx_fault0 ));

  \04_#20sfp_module  page1_3p  (.los(\sfp.los1 ),
	.rate_select(\sfp.rate_select1 ),
	.rd_n(\sfp.rd_n1 ),
	.rd_p(\sfp.rd_p1 ),
	.scl(\sfp.scl1 ),
	.sda(\sfp.sda1 ),
	.td_n(\sfp.td_n1 ),
	.td_p(\sfp.td_p1 ),
	.tx_disable(\sfp.tx_disable1 ),
	.tx_fault(\sfp.tx_fault1 ));

  \04_#20sfp_module  page1_4p  (.los(\sfp.los2 ),
	.rate_select(\sfp.rate_select2 ),
	.rd_n(\sfp.rd_n2 ),
	.rd_p(\sfp.rd_p2 ),
	.scl(\sfp.scl2 ),
	.sda(\sfp.sda2 ),
	.td_n(\sfp.td_n2 ),
	.td_p(\sfp.td_p2 ),
	.tx_disable(\sfp.tx_disable2 ),
	.tx_fault(\sfp.tx_fault2 ));

endmodule // \03_#20sfp (sch_1) 
