
// generated by NetAssembler Version 17.4-2019 S031 (4044358) 7/23/2022 
// on Sat Dec 31 17:29:56 2022


`timescale 1ns/1ns

`define scale_fs	* 0.000001000000000
`define scale_ps	* 0.001000000000000
`define scale_ns	* 1.000000000000000
`define scale_us	* 1000.000000000000000
`define scale_ms	* 1000000.000000000000000
`define scale_sec	* 1000000000.000000000000000
`define scale_min	* 60000000000.000000000000000
`define scale_hr	* 3600000000000.000000000000000



module alias_vector (a, a);
 parameter size = 1;
 inout [size-1:0] a;
endmodule

module alias_bit (a, a);
 inout a;
endmodule


module glbl ();
// Verilog global signals module 
`ifdef VAN
	wire gnd;
`else
	supply0 gnd;
`endif
  wire mp3v3;
  wire vcc3v3;
  wire vcc3v3_iv;
  wire vin3v5_dcdc;
  wire vp12;
  wire vp1v8;
  wire vp1v8_iv;
  wire vp3v3;
  wire vp3v3_iv;
  wire vp3v5;
  wire vref_jtag;
endmodule
