// generated by newgenasym  Mon May 11 17:25:27 2015


module \854s01i  (clk_sel, npclk, nq, pclk, q, reserved);
    input clk_sel;
    input [1:0] npclk;
    output nq;
    input [1:0] pclk;
    output q;
    input reserved;


    initial
        begin
        end

endmodule
