-- generated by newgenasym Mon May 11 17:25:27 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \854s01i\ is
    port (    
	CLK_SEL:   IN     STD_LOGIC;    
	NPCLK:     IN     STD_LOGIC_VECTOR (1 DOWNTO 0);    
	NQ:        OUT    STD_LOGIC;    
	PCLK:      IN     STD_LOGIC_VECTOR (1 DOWNTO 0);    
	Q:         OUT    STD_LOGIC;    
	RESERVED:  IN     STD_LOGIC);
end \854s01i\;
