`timescale 1ns/1ns

module \08_#20timing  (bp, sfp, timing );
// generated by  HDL Direct 17.4-2019 S031 (4044358) 7/23/2022
// on Sat Dec 31 17:29:54 2022
// from mtca_interface_board_reocc/08_ TIMING/sch_1

  inout [180:0] bp;
  inout [29:0] sfp;
  inout [27:0] timing;
  // global signal glbl.gnd;
  // global signal glbl.vcc3v3;
  // global signal glbl.vp1v8;

  wire  \bp.ref_clk_n0 ;
  wire  \bp.ref_clk_n1 ;
  wire  \bp.ref_clk_n10 ;
  wire  \bp.ref_clk_n11 ;
  wire  \bp.ref_clk_n2 ;
  wire  \bp.ref_clk_n3 ;
  wire  \bp.ref_clk_n4 ;
  wire  \bp.ref_clk_n5 ;
  wire  \bp.ref_clk_n6 ;
  wire  \bp.ref_clk_n7 ;
  wire  \bp.ref_clk_n8 ;
  wire  \bp.ref_clk_n9 ;
  wire  \bp.ref_clk_p0 ;
  wire  \bp.ref_clk_p1 ;
  wire  \bp.ref_clk_p10 ;
  wire  \bp.ref_clk_p11 ;
  wire  \bp.ref_clk_p2 ;
  wire  \bp.ref_clk_p3 ;
  wire  \bp.ref_clk_p4 ;
  wire  \bp.ref_clk_p5 ;
  wire  \bp.ref_clk_p6 ;
  wire  \bp.ref_clk_p7 ;
  wire  \bp.ref_clk_p8 ;
  wire  \bp.ref_clk_p9 ;
  wire  cdr0_clkgen_n;
  wire  cdr0_clkgen_p;
  wire  cdr0_clkout_n;
  wire  cdr0_clkout_p;
  wire  cdr0_in_n;
  wire  cdr0_in_p;
  wire  cdr0_vcc3v3;
  wire  cdr1_clkgen_n;
  wire  cdr1_clkgen_p;
  wire  cdr1_clkout_n;
  wire  cdr1_clkout_p;
  wire  cdr1_in_n;
  wire  cdr1_in_p;
  wire  cdr1_vcc3v3;
  wire  clk_n0;
  wire  clk_n1;
  wire  clk_n2;
  wire  clk_out_n0;
  wire  clk_out_p0;
  wire  clk_p0;
  wire  clk_p1;
  wire  clk_p2;
  wire  dff_data_out_n;
  wire  dff_data_out_p;
  wire  dff_in_n;
  wire  dff_in_p;
  wire  dff_ref_clk_n;
  wire  dff_ref_clk_p;
  wire  fbclk_n;
  wire  fbclk_p;
  wire  i2c_sel;
  wire  n00871;
  wire  n00873;
  wire  n00879;
  wire  n00881;
  wire  n00883;
  wire  n00885;
  wire  n00891;
  wire  n00899;
  wire  n00907;
  wire  n00913;
  wire  n00921;
  wire  n00927;
  wire  n00935;
  wire  n00943;
  wire  n00945;
  wire  n00951;
  wire  n00953;
  wire  n00955;
  wire  n02371;
  wire  rclk_n0;
  wire  rclk_n1;
  wire  rclk_p0;
  wire  rclk_p1;
  wire  refclk_out0_n;
  wire  refclk_out0_p;
  wire  refclk_out1_n;
  wire  refclk_out1_p;
  wire  rsel;
  wire  scope_n;
  wire  scope_p;
  wire  \sfp.rd_n1 ;
  wire  \sfp.rd_n2 ;
  wire  \sfp.rd_p1 ;
  wire  \sfp.rd_p2 ;
  wire  \sfp.td_n1 ;
  wire  \sfp.td_n2 ;
  wire  \sfp.td_p1 ;
  wire  \sfp.td_p2 ;
  wire  thradj1;
  wire  thradj2;
  wire  \timing.cdr_clk_in_n0 ;
  wire  \timing.cdr_clk_in_n1 ;
  wire  \timing.cdr_clk_in_n2 ;
  wire  \timing.cdr_clk_in_p0 ;
  wire  \timing.cdr_clk_in_p1 ;
  wire  \timing.cdr_clk_in_p2 ;
  wire  \timing.cdr_data_in_n0 ;
  wire  \timing.cdr_data_in_n1 ;
  wire  \timing.cdr_data_in_p0 ;
  wire  \timing.cdr_data_in_p1 ;
  wire  \timing.cdr_lol0 ;
  wire  \timing.cdr_lol1 ;
  wire  \timing.cdr_los0 ;
  wire  \timing.cdr_los1 ;
  wire  \timing.clkgen_intr ;
  wire  \timing.clkgen_lol ;
  wire  \timing.clkgen_rst ;
  wire  \timing.clk_i2c_scl ;
  wire  \timing.clk_i2c_sda ;
  wire  \timing.clk_sel0 ;
  wire  \timing.clk_sel1 ;
  wire  \timing.sfp_sel0 ;
  wire  \timing.sfp_sel1 ;
  wire  \timing.upstream_data_n0 ;
  wire  \timing.upstream_data_n1 ;
  wire  \timing.upstream_data_p0 ;
  wire  \timing.upstream_data_p1 ;
  wire  udata_in_n;
  wire  udata_in_p;
  wire  \vdd1_clk-buffer ;
  wire  \vdd2_clk-buffer ;
  wire  vdda_clk;
  wire  vdd_clk;
  wire  vref1;
  wire  vref2;
  wire  vtclk;
  wire  vtd;
  wire  xa;
  wire  xb;
  wire  xgnd;
  wire [11:0] \bp.ref_clk_n ;
  wire [11:0] \bp.ref_clk_p ;
  wire [2:0] \sfp.los ;
  wire [2:0] \sfp.rate_select ;
  wire [2:0] \sfp.rd_n ;
  wire [2:0] \sfp.rd_p ;
  wire [2:0] \sfp.scl ;
  wire [2:0] \sfp.sda ;
  wire [2:0] \sfp.td_n ;
  wire [2:0] \sfp.td_p ;
  wire [2:0] \sfp.tx_disable ;
  wire [2:0] \sfp.tx_fault ;
  wire [2:0] \timing.cdr_clk_in_n ;
  wire [2:0] \timing.cdr_clk_in_p ;
  wire [1:0] \timing.cdr_data_in_n ;
  wire [1:0] \timing.cdr_data_in_p ;
  wire [1:0] \timing.cdr_lol ;
  wire [1:0] \timing.cdr_los ;
  wire [2:0] \timing.sfp_sel ;
  wire [1:0] \timing.upstream_data_n ;
  wire [1:0] \timing.upstream_data_p ;

  wire [180:0] page3_bp;
  wire  gnd;
  wire  page3_gnd;
  wire  page2_gnd;
  wire  page1_gnd;
  wire [29:0] page1_sfp;
  wire [27:0] page1_timing;
  wire  \page1_timing.clkgen_intr ;
  wire  \page1_timing.clkgen_lol ;
  wire  \page1_timing.clkgen_rst ;
  wire  \page1_timing.clk_sel0 ;
  wire  \page1_timing.clk_sel1 ;
  wire  vcc3v3;
  wire  page3_vcc3v3;
  wire  page2_vcc3v3;
  wire  page1_vcc3v3;
  wire  vp1v8;
  wire  page2_vp1v8;

  assign page3_bp[180:0] = bp[180:0];
  assign page3_bp[180:0] = bp[180:0];
  assign gnd = glbl.gnd;
  assign page3_gnd = gnd;
  assign page2_gnd = gnd;
  assign page1_gnd = gnd;
  assign page1_sfp[29:0] = sfp[29:0];
  assign page1_sfp[29:0] = sfp[29:0];
  assign page1_timing[27:0] = timing[27:0];
  assign page1_timing[27:0] = timing[27:0];
  assign \page1_timing.clkgen_intr  = \timing.clkgen_intr ;
  assign \page1_timing.clkgen_lol  = \timing.clkgen_lol ;
  assign \page1_timing.clkgen_rst  = \timing.clkgen_rst ;
  assign \page1_timing.clk_sel0  = \timing.clk_sel0 ;
  assign \page1_timing.clk_sel1  = \timing.clk_sel1 ;
  assign vcc3v3 = glbl.vcc3v3;
  assign page3_vcc3v3 = vcc3v3;
  assign page2_vcc3v3 = vcc3v3;
  assign page1_vcc3v3 = vcc3v3;
  assign vp1v8 = glbl.vp1v8;
  assign page2_vp1v8 = vp1v8;

  assign gnd  = glbl.gnd;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign \timing.clk_i2c_scl   = timing[0];
  assign vcc3v3  = glbl.vcc3v3;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign \timing.clk_i2c_sda   = timing[1];
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign gnd  = glbl.gnd;
  assign vcc3v3  = glbl.vcc3v3;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign \timing.clk_sel0   = timing[2];
  assign \timing.clk_sel1   = timing[3];
  assign \timing.clkgen_intr   = timing[4];
  assign \timing.clkgen_lol   = timing[5];
  assign \timing.clkgen_rst   = timing[6];
  assign gnd  = glbl.gnd;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign vp1v8  = glbl.vp1v8;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  r page1_333p  (.\1 (glbl.gnd),
	.\2 (\timing.sfp_sel0 ));

  r page1_334p  (.\1 (glbl.vcc3v3),
	.\2 (n00883));

  cap_np page1_335p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_336p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_337p  (.\1 (cdr1_vcc3v3),
	.\2 (glbl.gnd));

  r page1_338p  (.\1 (glbl.vcc3v3),
	.\2 (n00943));

  r page1_339p  (.\1 (\sfp.rd_p2 ),
	.\2 (cdr1_in_p));

  r page1_340p  (.\1 (\timing.sfp_sel1 ),
	.\2 (glbl.vcc3v3));

  cap_np_0 page1_341p  (.\1 (dff_ref_clk_p),
	.\2 (dff_in_p));

  r page1_342p  (.\1 (rsel),
	.\2 (glbl.vcc3v3));

  cap_np page1_343p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_344p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  r page1_345p  (.\1 (\timing.upstream_data_p1 ),
	.\2 (\timing.upstream_data_n1 ));

  cap_np_0 page1_346p  (.\1 (\timing.upstream_data_p0 ),
	.\2 (udata_in_p));

  r page1_347p  (.\1 (glbl.vcc3v3),
	.\2 (n00879));

  cap_np page1_348p  (.\1 (cdr1_vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_349p  (.\1 (cdr0_vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_350p  (.\1 (cdr0_vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_351p  (.\1 (cdr1_vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_352p  (.\1 (vref1),
	.\2 (glbl.gnd));

  cap_np page1_353p  (.\1 (cdr1_vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_354p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_355p  (.\1 (n00953),
	.\2 (n00945));

  r page1_356p  (.\1 (glbl.gnd),
	.\2 (n00935));

  cap_np page1_357p  (.\1 (cdr1_vcc3v3),
	.\2 (glbl.gnd));

  r page1_358p  (.\1 (n00921),
	.\2 (glbl.gnd));

  r page1_359p  (.\1 (dff_data_out_p),
	.\2 (dff_data_out_n));

  max9152ese_t page1_360p  (.en0(n00891),
	.en1(n00891),
	.gnd(glbl.gnd),
	.\in0+ (cdr0_clkout_p),
	.\in0- (cdr0_clkout_n),
	.\in1+ (/* unconnected */),
	.\in1- (/* unconnected */),
	.nc(/* unconnected */),
	.\out0+ (\timing.cdr_clk_in_p0 ),
	.\out0- (\timing.cdr_clk_in_n0 ),
	.\out1+ (cdr0_clkgen_p),
	.\out1- (cdr0_clkgen_n),
	.rsel(n00907),
	.sel0(n00899),
	.sel1(n00899),
	.vcc(glbl.vcc3v3));

  cap_np page1_361p  (.\1 (cdr0_vcc3v3),
	.\2 (glbl.gnd));

  r page1_362p  (.\1 (\sfp.rd_p1 ),
	.\2 (cdr0_in_p));

  cap_np page1_363p  (.\1 (cdr0_vcc3v3),
	.\2 (glbl.gnd));

  r page1_364p  (.\1 (n00891),
	.\2 (glbl.vcc3v3));

  cap_np page1_365p  (.\1 (cdr0_vcc3v3),
	.\2 (glbl.gnd));

  r page1_366p  (.\1 (n00907),
	.\2 (glbl.vcc3v3));

  cap_np page1_367p  (.\1 (cdr0_vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_368p  (.\1 (cdr0_vcc3v3),
	.\2 (glbl.gnd));

  r page1_369p  (.\1 (n00927),
	.\2 (glbl.vcc3v3));

  r page1_370p  (.\1 (glbl.gnd),
	.\2 (thradj2));

  cap_np page1_371p  (.\1 (cdr0_vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_372p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_373p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_374p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np_0 page1_375p  (.\1 (dff_ref_clk_n),
	.\2 (dff_in_n));

  cap_np_0 page1_376p  (.\1 (\timing.upstream_data_n0 ),
	.\2 (udata_in_n));

  max9152ese_t page1_377p  (.en0(n00913),
	.en1(n00913),
	.gnd(glbl.gnd),
	.\in0+ (dff_data_out_p),
	.\in0- (dff_data_out_n),
	.\in1+ (\timing.upstream_data_p1 ),
	.\in1- (\timing.upstream_data_n1 ),
	.nc(/* unconnected */),
	.\out0+ (\sfp.td_p1 ),
	.\out0- (\sfp.td_n1 ),
	.\out1+ (\sfp.td_p2 ),
	.\out1- (\sfp.td_n2 ),
	.rsel(rsel),
	.sel0(\timing.sfp_sel0 ),
	.sel1(\timing.sfp_sel1 ),
	.vcc(glbl.vcc3v3));

  r page1_378p  (.\1 (glbl.gnd),
	.\2 (n00951));

  adn2814acpz page1_379p  (.cf1(n00871),
	.cf2(n00873),
	.clkoutn(cdr0_clkout_n),
	.clkoutp(cdr0_clkout_p),
	.dataoutn(\timing.cdr_data_in_n0 ),
	.dataoutp(\timing.cdr_data_in_p0 ),
	.lol(\timing.cdr_lol0 ),
	.los(\timing.cdr_los0 ),
	.nin(cdr0_in_n),
	.pad(glbl.gnd),
	.pin(cdr0_in_p),
	.refclkn(n00881),
	.refclkp(n00879),
	.saddr5(glbl.gnd),
	.sck(\timing.clk_i2c_scl ),
	.sda(\timing.clk_i2c_sda ),
	.slicen(glbl.gnd),
	.slicep(glbl.gnd),
	.squelch(glbl.gnd),
	.thradj(thradj1),
	.vcc1(cdr0_vcc3v3),
	.vcc2(cdr0_vcc3v3),
	.vcc3(cdr0_vcc3v3),
	.vcc4(cdr0_vcc3v3),
	.vcc5(cdr0_vcc3v3),
	.vcc6(cdr0_vcc3v3),
	.vcc7(cdr0_vcc3v3),
	.vee1(glbl.gnd),
	.vee2(glbl.gnd),
	.vee3(glbl.gnd),
	.vee4(glbl.gnd),
	.vee5(glbl.gnd),
	.vref(vref1));

  cap_np page1_380p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_381p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_382p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_383p  (.\1 (cdr1_vcc3v3),
	.\2 (glbl.gnd));

  r page1_384p  (.\1 (\sfp.rd_n1 ),
	.\2 (cdr0_in_n));

  r page1_385p  (.\1 (glbl.gnd),
	.\2 (n00885));

  r page1_386p  (.\1 (rsel),
	.\2 (glbl.gnd));

  r page1_387p  (.\1 (\sfp.rd_n2 ),
	.\2 (cdr1_in_n));

  nbsg53amng page1_388p  (.clk(dff_in_p),
	.clkb(dff_in_n),
	.d(udata_in_p),
	.db(udata_in_n),
	.gnd_pad(glbl.gnd),
	.ols(n00885),
	.q(dff_data_out_p),
	.qb(dff_data_out_n),
	.r(/* unconnected */),
	.sel(n00883),
	.vcc1(glbl.vcc3v3),
	.vcc2(glbl.vcc3v3),
	.vee(glbl.gnd),
	.vtclk(vtclk),
	.vtclkb(vtclk),
	.vtd(vtd),
	.vtdb(vtd));

  r page1_389p  (.\1 (glbl.gnd),
	.\2 (thradj1));

  r page1_390p  (.\1 (n00913),
	.\2 (glbl.vcc3v3));

  r page1_391p  (.\1 (glbl.gnd),
	.\2 (n00881));

  cap_np page1_392p  (.\1 (vref2),
	.\2 (glbl.gnd));

  r page1_393p  (.\1 (glbl.vcc3v3),
	.\2 (n00955));

  adn2814acpz page1_394p  (.cf1(n00953),
	.cf2(n00945),
	.clkoutn(cdr1_clkout_n),
	.clkoutp(cdr1_clkout_p),
	.dataoutn(\timing.cdr_data_in_n1 ),
	.dataoutp(\timing.cdr_data_in_p1 ),
	.lol(\timing.cdr_lol1 ),
	.los(\timing.cdr_los1 ),
	.nin(cdr1_in_n),
	.pad(glbl.gnd),
	.pin(cdr1_in_p),
	.refclkn(n00951),
	.refclkp(n00943),
	.saddr5(n00955),
	.sck(\timing.clk_i2c_scl ),
	.sda(\timing.clk_i2c_sda ),
	.slicen(glbl.gnd),
	.slicep(glbl.gnd),
	.squelch(glbl.gnd),
	.thradj(thradj2),
	.vcc1(cdr1_vcc3v3),
	.vcc2(cdr1_vcc3v3),
	.vcc3(cdr1_vcc3v3),
	.vcc4(cdr1_vcc3v3),
	.vcc5(cdr1_vcc3v3),
	.vcc6(cdr1_vcc3v3),
	.vcc7(cdr1_vcc3v3),
	.vee1(glbl.gnd),
	.vee2(glbl.gnd),
	.vee3(glbl.gnd),
	.vee4(glbl.gnd),
	.vee5(glbl.gnd),
	.vref(vref2));

  cap_np page1_395p  (.\1 (n00871),
	.\2 (n00873));

  cap_np page1_396p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  r page1_397p  (.\1 (glbl.gnd),
	.\2 (n00899));

  cap_np page1_398p  (.\1 (cdr0_vcc3v3),
	.\2 (glbl.gnd));

  ind page1_399p  (.\1 (glbl.vcc3v3),
	.\2 (cdr1_vcc3v3));

  cap_np page1_400p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_401p  (.\1 (cdr1_vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_402p  (.\1 (cdr1_vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_403p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_404p  (.\1 (cdr1_vcc3v3),
	.\2 (glbl.gnd));

  cap_np page1_405p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  r page1_406p  (.\1 (cdr1_clkout_p),
	.\2 (cdr1_clkout_n));

  r page1_407p  (.\1 (n00907),
	.\2 (glbl.gnd));

  max9152ese_t page1_408p  (.en0(n00927),
	.en1(n00927),
	.gnd(glbl.gnd),
	.\in0+ (cdr1_clkout_p),
	.\in0- (cdr1_clkout_n),
	.\in1+ (/* unconnected */),
	.\in1- (/* unconnected */),
	.nc(/* unconnected */),
	.\out0+ (cdr1_clkgen_p),
	.\out0- (cdr1_clkgen_n),
	.\out1+ (\timing.cdr_clk_in_p1 ),
	.\out1- (\timing.cdr_clk_in_n1 ),
	.rsel(n00921),
	.sel0(n00935),
	.sel1(n00935),
	.vcc(glbl.vcc3v3));

  r page1_409p  (.\1 (n00921),
	.\2 (glbl.vcc3v3));

  r page1_410p  (.\1 (cdr0_clkout_p),
	.\2 (cdr0_clkout_n));

  ind page1_411p  (.\1 (glbl.vcc3v3),
	.\2 (cdr0_vcc3v3));

  cap_np_0 page2_259p  (.\1 (cdr1_clkgen_p),
	.\2 (clk_p1));

  testpoint page2_260p  (.tp(scope_n));

  cap_np page2_261p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  cap_np_0 page2_262p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  ind page2_263p  (.\1 (glbl.vcc3v3),
	.\2 (vdda_clk));

  \4-smd_crystal  page2_264p  (.gnd1(xgnd),
	.gnd2(xgnd),
	.hot1(xb),
	.hot2(xa));

  cap_np page2_265p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  cap_np_0 page2_266p  (.\1 (cdr0_clkgen_p),
	.\2 (clk_p0));

  cap_np page2_267p  (.\1 (vdd_clk),
	.\2 (glbl.gnd));

  ind page2_268p  (.\1 (glbl.vp1v8),
	.\2 (vdd_clk));

  r page2_269p  (.\1 (clk_out_p0),
	.\2 (scope_p));

  r page2_270p  (.\1 (glbl.gnd),
	.\2 (n02371));

  cap_np_0 page2_271p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  cap_np page2_272p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  cap_np page2_273p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  cap_np page2_274p  (.\1 (clk_out_p0),
	.\2 (glbl.gnd));

  cap_np page2_275p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  cap_np_0 page2_276p  (.\1 (fbclk_n),
	.\2 (clk_n2));

  cap_np page2_277p  (.\1 (vdd_clk),
	.\2 (glbl.gnd));

  r page2_278p  (.\1 (\timing.clkgen_rst ),
	.\2 (glbl.vcc3v3));

  r page2_279p  (.\1 (glbl.vcc3v3),
	.\2 (i2c_sel));

  cap_np page2_280p  (.\1 (vdd_clk),
	.\2 (glbl.gnd));

  cap_np_0 page2_281p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  cap_np page2_282p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  cap_np page2_283p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  cap_np page2_284p  (.\1 (clk_out_n0),
	.\2 (glbl.gnd));

  \si5395a-a-gm  page2_285p  (.\a0/csb (glbl.gnd),
	.\a1/sdo (glbl.gnd),
	.fdec(glbl.gnd),
	.finc(glbl.gnd),
	.gnd_pad(glbl.gnd),
	.i2c_sel(i2c_sel),
	.in0(clk_p0),
	.in0b(clk_n0),
	.in1(clk_p1),
	.in1b(clk_n1),
	.in2(/* unconnected */),
	.in2b(/* unconnected */),
	.\in3/fb_in (clk_p2),
	.\in3b/fb_inb (clk_n2),
	.intrb(\timing.clkgen_intr ),
	.in_sel0(\timing.clk_sel0 ),
	.in_sel1(\timing.clk_sel1 ),
	.lolb(\timing.clkgen_lol ),
	.oeb(n02371),
	.out0(refclk_out0_p),
	.out0a(/* unconnected */),
	.out0ab(/* unconnected */),
	.out0b(refclk_out0_n),
	.out1(refclk_out1_p),
	.out1b(refclk_out1_n),
	.out2(dff_ref_clk_p),
	.out2b(dff_ref_clk_n),
	.out3(\timing.cdr_clk_in_p2 ),
	.out3b(\timing.cdr_clk_in_n2 ),
	.out4(/* unconnected */),
	.out4b(/* unconnected */),
	.out5(clk_out_p0),
	.out5b(clk_out_n0),
	.out6(/* unconnected */),
	.out6b(/* unconnected */),
	.out7(/* unconnected */),
	.out7b(/* unconnected */),
	.out8(fbclk_p),
	.out8b(fbclk_n),
	.out9(/* unconnected */),
	.out9a(/* unconnected */),
	.out9ab(/* unconnected */),
	.out9b(/* unconnected */),
	.rstb(\timing.clkgen_rst ),
	.rsvd(/* unconnected */),
	.sclk(\timing.clk_i2c_sda ),
	.\sda/sdio (\timing.clk_i2c_scl ),
	.vdd0(vdd_clk),
	.vdd1(vdd_clk),
	.vdd2(vdd_clk),
	.vdda(vdda_clk),
	.vddo0(vdda_clk),
	.vddo1(vdda_clk),
	.vddo2(vdda_clk),
	.vddo3(vdda_clk),
	.vddo4(/* unconnected */),
	.vddo5(vdda_clk),
	.vddo6(/* unconnected */),
	.vddo7(/* unconnected */),
	.vddo8(vdda_clk),
	.vddo9(/* unconnected */),
	.\x1/nc (xgnd),
	.\x2/nc (xgnd),
	.\xa/nc (xa),
	.\xb/nc (xb));

  cap_np_0 page2_286p  (.\1 (cdr0_clkgen_n),
	.\2 (clk_n0));

  cap_np_0 page2_287p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  r page2_288p  (.\1 (clk_out_n0),
	.\2 (scope_n));

  cap_np page2_289p  (.\1 (vdd_clk),
	.\2 (glbl.gnd));

  cap_np_0 page2_290p  (.\1 (cdr1_clkgen_n),
	.\2 (clk_n1));

  cap_np page2_291p  (.\1 (glbl.vp1v8),
	.\2 (glbl.gnd));

  cap_np_0 page2_292p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  cap_np page2_293p  (.\1 (vdd_clk),
	.\2 (glbl.gnd));

  cap_np page2_294p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  cap_np page2_295p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  r page2_296p  (.\1 (scope_n),
	.\2 (glbl.gnd));

  testpoint page2_297p  (.tp(glbl.gnd));

  r page2_298p  (.\1 (clk_p2),
	.\2 (clk_n2));

  r page2_299p  (.\1 (scope_p),
	.\2 (glbl.gnd));

  cap_np page2_300p  (.\1 (vdd_clk),
	.\2 (glbl.gnd));

  r page2_301p  (.\1 (clk_p0),
	.\2 (clk_n0));

  r page2_302p  (.\1 (clk_p1),
	.\2 (clk_n1));

  cap_np_0 page2_303p  (.\1 (vdda_clk),
	.\2 (glbl.gnd));

  testpoint page2_304p  (.tp(glbl.gnd));

  cap_np_0 page2_305p  (.\1 (fbclk_p),
	.\2 (clk_p2));

  testpoint page2_306p  (.tp(scope_p));

  cap_np page2_307p  (.\1 (vdd_clk),
	.\2 (glbl.gnd));

  cap_np page2_308p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  cap_np page3_135p  (.\1 (\vdd2_clk-buffer ),
	.\2 (glbl.gnd));

  cap_np page3_136p  (.\1 (\vdd1_clk-buffer ),
	.\2 (glbl.gnd));

  cap_np_0 page3_137p  (.\1 (refclk_out1_p),
	.\2 (rclk_p1));

  cap_np page3_138p  (.\1 (\vdd2_clk-buffer ),
	.\2 (glbl.gnd));

  cap_np page3_139p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  ind page3_140p  (.\1 (glbl.vcc3v3),
	.\2 (\vdd2_clk-buffer ));

  cap_np page3_141p  (.\1 (\vdd1_clk-buffer ),
	.\2 (glbl.gnd));

  cap_np page3_142p  (.\1 (\vdd2_clk-buffer ),
	.\2 (glbl.gnd));

  cap_np page3_143p  (.\1 (\vdd1_clk-buffer ),
	.\2 (glbl.gnd));

  cap_np page3_144p  (.\1 (\vdd2_clk-buffer ),
	.\2 (glbl.gnd));

  cap_np_0 page3_145p  (.\1 (refclk_out0_n),
	.\2 (rclk_n0));

  cap_np_0 page3_146p  (.\1 (refclk_out1_n),
	.\2 (rclk_n1));

  cap_np page3_147p  (.\1 (\vdd2_clk-buffer ),
	.\2 (glbl.gnd));

  cap_np page3_148p  (.\1 (\vdd1_clk-buffer ),
	.\2 (glbl.gnd));

  \si53342-b-gm  page3_149p  (.clk0(rclk_p1),
	.clk0b(rclk_n1),
	.clk1(/* unconnected */),
	.clk1b(/* unconnected */),
	.clk_sel(glbl.gnd),
	.gnd_pad(glbl.gnd),
	.nc1(/* unconnected */),
	.nc2(/* unconnected */),
	.oeab(/* unconnected */),
	.oebb(/* unconnected */),
	.q0(\bp.ref_clk_p6 ),
	.q0b(\bp.ref_clk_n6 ),
	.q1(\bp.ref_clk_p7 ),
	.q1b(\bp.ref_clk_n7 ),
	.q2(\bp.ref_clk_p8 ),
	.q2b(\bp.ref_clk_n8 ),
	.q3(\bp.ref_clk_p9 ),
	.q3b(\bp.ref_clk_n9 ),
	.q4(\bp.ref_clk_p10 ),
	.q4b(\bp.ref_clk_n10 ),
	.q5(\bp.ref_clk_p11 ),
	.q5b(\bp.ref_clk_n11 ),
	.vdd(\vdd2_clk-buffer ),
	.vddoa(\vdd2_clk-buffer ),
	.vddob(\vdd2_clk-buffer ));

  ind page3_150p  (.\1 (glbl.vcc3v3),
	.\2 (\vdd1_clk-buffer ));

  cap_np page3_151p  (.\1 (\vdd1_clk-buffer ),
	.\2 (glbl.gnd));

  cap_np page3_152p  (.\1 (\vdd2_clk-buffer ),
	.\2 (glbl.gnd));

  cap_np page3_153p  (.\1 (\vdd1_clk-buffer ),
	.\2 (glbl.gnd));

  cap_np page3_154p  (.\1 (\vdd2_clk-buffer ),
	.\2 (glbl.gnd));

  cap_np page3_155p  (.\1 (\vdd1_clk-buffer ),
	.\2 (glbl.gnd));

  r page3_156p  (.\1 (rclk_p0),
	.\2 (rclk_n0));

  cap_np page3_157p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  r page3_158p  (.\1 (rclk_p1),
	.\2 (rclk_n1));

  \si53342-b-gm  page3_159p  (.clk0(rclk_p0),
	.clk0b(rclk_n0),
	.clk1(/* unconnected */),
	.clk1b(/* unconnected */),
	.clk_sel(glbl.gnd),
	.gnd_pad(glbl.gnd),
	.nc1(/* unconnected */),
	.nc2(/* unconnected */),
	.oeab(/* unconnected */),
	.oebb(/* unconnected */),
	.q0(\bp.ref_clk_p0 ),
	.q0b(\bp.ref_clk_n0 ),
	.q1(\bp.ref_clk_p1 ),
	.q1b(\bp.ref_clk_n1 ),
	.q2(\bp.ref_clk_p2 ),
	.q2b(\bp.ref_clk_n2 ),
	.q3(\bp.ref_clk_p3 ),
	.q3b(\bp.ref_clk_n3 ),
	.q4(\bp.ref_clk_p4 ),
	.q4b(\bp.ref_clk_n4 ),
	.q5(\bp.ref_clk_p5 ),
	.q5b(\bp.ref_clk_n5 ),
	.vdd(\vdd1_clk-buffer ),
	.vddoa(\vdd1_clk-buffer ),
	.vddob(\vdd1_clk-buffer ));

  cap_np_0 page3_160p  (.\1 (refclk_out0_p),
	.\2 (rclk_p0));

endmodule // \08_#20timing (sch_1) 
