-- generated by newgenasym Mon Jul 29 12:45:09 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \shf-105-01-l-d-ra\ is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (9 DOWNTO 0));
end \shf-105-01-l-d-ra\;
