// generated by newgenasym  Mon May 21 10:35:03 2012


module \usblc6-2  (gnd, \i/o1 , \i/o2 , vbus);
    input gnd;
    inout [1:0] \i/o1 ;
    inout [1:0] \i/o2 ;
    input vbus;


    initial
        begin
        end

endmodule
