-- generated by newgenasym Fri Jun 21 11:27:11 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ss16fp is
    port (    
	A:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC);
end ss16fp;
