-- generated by newgenasym Fri Jun 26 11:16:55 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TP is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end TP;
