// generated by newgenasym  Wed Jul  3 07:30:18 2024


module \08_#20timing  (bp, clkgen_io, data_select_p2v5, direct_us_data_2_n,
        direct_us_data_2_p, sfp, sfp_data_io);
    inout [180:0] bp;
    inout [10:0] clkgen_io;
    inout data_select_p2v5;
    inout direct_us_data_2_n;
    inout direct_us_data_2_p;
    inout [29:0] sfp;
    inout [11:0] sfp_data_io;


    initial
        begin
        end

endmodule
