// generated by newgenasym  Tue Jul  2 15:09:26 2024


module \08_#20timing  (bp, clkgen_io, sfp, sfp_data_io, trenzdata);
    inout [180:0] bp;
    inout [10:0] clkgen_io;
    inout [29:0] sfp;
    inout [11:0] sfp_data_io;
    inout [3:0] trenzdata;


    initial
        begin
        end

endmodule
