// generated by newgenasym  Fri Jan 27 10:18:47 2023


module \08_#20timing  (bp, clkgen_io, sfp, sfp_data_io);
    inout [180:0] bp;
    inout [10:0] clkgen_io;
    inout [29:0] sfp;
    inout [11:0] sfp_data_io;


    initial
        begin
        end

endmodule
