-- generated by newgenasym Tue Jul  2 15:09:26 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \08_ timing\ is
    port (    
	BP:        INOUT  std_logic_vector (180 DOWNTO 0);    
	CLKGEN_IO: INOUT  std_logic_vector (10 DOWNTO 0);    
	SFP:       INOUT  std_logic_vector (29 DOWNTO 0);    
	SFP_DATA_IO: INOUT  std_logic_vector (11 DOWNTO 0);    
	TRENZDATA: INOUT  std_logic_vector (3 DOWNTO 0));
end \08_ timing\;
