-- generated by newgenasym Fri Jan 27 10:18:47 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \08_ timing\ is
    port (    
	BP:        INOUT  std_logic_vector (180 DOWNTO 0);    
	CLKGEN_IO: INOUT  std_logic_vector (10 DOWNTO 0);    
	SFP:       INOUT  std_logic_vector (29 DOWNTO 0);    
	SFP_DATA_IO: INOUT  std_logic_vector (11 DOWNTO 0));
end \08_ timing\;
