// generated by newgenasym  Fri Jul 26 16:46:19 2024


module con16p_usb_c_usb2 (cc1, cc2, \da+ , \da- , \db+ , \db- , gnd1, gnd2, gnd3, gnd4, sbu1,
        sbu2, shield1, shield2, shield3, shield4, vbus1, vbus2,
        vbus3, vbus4);
    inout cc1;
    inout cc2;
    inout \da+ ;
    inout \da- ;
    inout \db+ ;
    inout \db- ;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout sbu1;
    inout sbu2;
    inout shield1;
    inout shield2;
    inout shield3;
    inout shield4;
    inout vbus1;
    inout vbus2;
    inout vbus3;
    inout vbus4;


    initial
        begin
        end

endmodule
