-- generated by newgenasym Fri Jul 26 16:46:19 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity con16p_usb_c_usb2 is
    port (    
	CC1:       INOUT  STD_LOGIC;    
	CC2:       INOUT  STD_LOGIC;    
	\da+\:     INOUT  STD_LOGIC;    
	\da-\:     INOUT  STD_LOGIC;    
	\db+\:     INOUT  STD_LOGIC;    
	\db-\:     INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	SBU1:      INOUT  STD_LOGIC;    
	SBU2:      INOUT  STD_LOGIC;    
	SHIELD1:   INOUT  STD_LOGIC;    
	SHIELD2:   INOUT  STD_LOGIC;    
	SHIELD3:   INOUT  STD_LOGIC;    
	SHIELD4:   INOUT  STD_LOGIC;    
	VBUS1:     INOUT  STD_LOGIC;    
	VBUS2:     INOUT  STD_LOGIC;    
	VBUS3:     INOUT  STD_LOGIC;    
	VBUS4:     INOUT  STD_LOGIC);
end con16p_usb_c_usb2;
