// generated by newgenasym  Fri Sep 21 14:10:47 2001

`timescale 1ns/100ps

module capcersmdcl2 (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    CAP  inst1[size-1:0] (.A(a),
                               .B(b) );
endmodule
