`timescale 1ns/1ns

module \04_#20sfp_module  (los, \rd+ , \rd- , tx_fault, sda, rate_select, scl, \td+ , \td- , tx_disable );
// generated by  HDL Direct 17.4-2019 S031 (4044358) 7/23/2022
// on Sat Dec 31 17:29:53 2022
// from mtca_interface_board_reocc/04_ SFP_MODULE/sch_1

  output  los;
  output  \rd+ ;
  output  \rd- ;
  output  tx_fault;
  inout  sda;
  input  rate_select;
  input  scl;
  input  \td+ ;
  input  \td- ;
  input  tx_disable;
  // global signal glbl.gnd;
  // global signal glbl.vcc3v3;

  wire  n00183;
  wire  vccr_3v3;
  wire  vcct_3v3;

  wire  gnd;
  wire  page1_gnd;
  wire  page1_los;
  wire  page1_rate_select;
  wire  \page1_rd+ ;
  wire  \page1_rd- ;
  wire  page1_scl;
  wire  page1_sda;
  wire  \page1_td+ ;
  wire  \page1_td- ;
  wire  page1_tx_disable;
  wire  page1_tx_fault;
  wire  vcc3v3;
  wire  page1_vcc3v3;

  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign page1_los = los;
  assign page1_rate_select = rate_select;
  assign \page1_rd+  = \rd+ ;
  assign \page1_rd-  = \rd- ;
  assign page1_scl = scl;
  assign page1_sda = sda;
  assign \page1_td+  = \td+ ;
  assign \page1_td-  = \td- ;
  assign page1_tx_disable = tx_disable;
  assign page1_tx_fault = tx_fault;
  assign vcc3v3 = glbl.vcc3v3;
  assign page1_vcc3v3 = vcc3v3;

  assign gnd  = glbl.gnd;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;

// begin instances 

  cap_np page1_47p  (.\1 (vccr_3v3),
	.\2 (glbl.gnd));

  cap_np page1_48p  (.\1 (vcct_3v3),
	.\2 (glbl.gnd));

  cap_np page1_49p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  r page1_50p  (.\1 (glbl.vcc3v3),
	.\2 (tx_fault));

  r page1_51p  (.\1 (glbl.vcc3v3),
	.\2 (n00183));

  r page1_52p  (.\1 (glbl.vcc3v3),
	.\2 (los));

  cap_np page1_53p  (.\1 (vcct_3v3),
	.\2 (glbl.gnd));

  ind page1_54p  (.\1 (vcct_3v3),
	.\2 (glbl.vcc3v3));

  cap_np page1_55p  (.\1 (glbl.vcc3v3),
	.\2 (glbl.gnd));

  r page1_56p  (.\1 (glbl.vcc3v3),
	.\2 (rate_select));

  \con20p_sfp-1367073-1  page1_57p  (.los(los),
	.mod_def0(n00183),
	.mod_def1(scl),
	.mod_def2(sda),
	.rate_select(rate_select),
	.\rd+ (\rd+ ),
	.\rd- (\rd- ),
	.\td+ (\td+ ),
	.\td- (\td- ),
	.tx_disable(tx_disable),
	.tx_fault(tx_fault),
	.vccr(vccr_3v3),
	.vcct(vcct_3v3),
	.veer0(glbl.gnd),
	.veer1(glbl.gnd),
	.veer2(glbl.gnd),
	.veer3(glbl.gnd),
	.veet0(glbl.gnd),
	.veet1(glbl.gnd),
	.veet2(glbl.gnd));

  r page1_58p  (.\1 (glbl.vcc3v3),
	.\2 (tx_disable));

  cap_np page1_59p  (.\1 (vccr_3v3),
	.\2 (glbl.gnd));

  \sfp_cage-2227023-1  page1_60p  (.cg(glbl.gnd),
	.cg1(glbl.gnd),
	.cg2(glbl.gnd),
	.cg3(glbl.gnd),
	.cg4(glbl.gnd),
	.cg5(glbl.gnd),
	.cg6(glbl.gnd),
	.cg7(glbl.gnd),
	.cg8(glbl.gnd),
	.cg_0(glbl.gnd),
	.cg_1(glbl.gnd),
	.cg_2(glbl.gnd),
	.cg_3(glbl.gnd),
	.cg_4(glbl.gnd),
	.cg_5(glbl.gnd),
	.cg_6(glbl.gnd),
	.cg_7(glbl.gnd),
	.cg_8(glbl.gnd),
	.cg_9(glbl.gnd),
	.cg_10(glbl.gnd));

  cap_np page1_61p  (.\1 (vccr_3v3),
	.\2 (glbl.gnd));

  ind page1_62p  (.\1 (glbl.vcc3v3),
	.\2 (vccr_3v3));

endmodule // \04_#20sfp_module (sch_1) 
