// generated by newgenasym  Wed Feb 29 18:10:52 2012


module res_sr (c1, c2, s1, s2);
    parameter    size = 1;
    inout [size-1:0] c1;
    inout [size-1:0] c2;
    inout [size-1:0] s1;
    inout [size-1:0] s2;


    initial
        begin
        end

endmodule
