-- generated by newgenasym Wed Feb 29 18:10:52 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity RES_SR is
    generic (
        size:positive:= 1
            );
    port (    
	C1:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	C2:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S1:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	S2:        INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end RES_SR;
