// generated by newgenasym  Thu Jan 23 16:45:08 2020


module max9381_umax (clk_n, clk_p, d_n, d_p, q_n, q_p);
    input clk_n;
    input clk_p;
    input d_n;
    input d_p;
    output q_n;
    output q_p;


    initial
        begin
        end

endmodule
