-- generated by newgenasym Thu Jan 23 16:45:08 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max9381_umax is
    port (    
	CLK_N:     IN     STD_LOGIC;    
	CLK_P:     IN     STD_LOGIC;    
	D_N:       IN     STD_LOGIC;    
	D_P:       IN     STD_LOGIC;    
	Q_N:       OUT    STD_LOGIC;    
	Q_P:       OUT    STD_LOGIC);
end max9381_umax;
