// generated by newgenasym  Thu Nov 13 16:34:18 2014


module adclk948 (clk0, \clk0* , clk1, \clk1* , in_sel, q, \q* , vref0, vref1, vt0,
        vt1);
    input clk0;
    input \clk0* ;
    input clk1;
    input \clk1* ;
    input in_sel;
    input [7:0] q;
    input [7:0] \q* ;
    input vref0;
    input vref1;
    input vt0;
    input vt1;


    initial
        begin
        end

endmodule
