-- generated by newgenasym Thu Nov 13 16:34:18 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ADCLK948 is
    port (    
	CLK0:      IN     STD_LOGIC;    
	\clk0*\:   IN     STD_LOGIC;    
	CLK1:      IN     STD_LOGIC;    
	\clk1*\:   IN     STD_LOGIC;    
	IN_SEL:    IN     STD_LOGIC;    
	Q:         IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\q*\:      IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	VREF0:     IN     STD_LOGIC;    
	VREF1:     IN     STD_LOGIC;    
	VT0:       IN     STD_LOGIC;    
	VT1:       IN     STD_LOGIC);
end ADCLK948;
