-- generated by newgenasym Fri Apr 03 18:41:58 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CAPCERSMDCL2 is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end CAPCERSMDCL2;
