`timescale 1ns/1ns

module \02_#20power  (power, fpga_pg );
// generated by  HDL Direct 17.4-2019 S031 (4044358) 7/23/2022
// on Sat Dec 31 17:29:55 2022
// from mtca_interface_board_reocc/02_ POWER/sch_1

  inout [10:0] power;
  input  fpga_pg;
  // global signal glbl.gnd;
  // global signal glbl.mp3v3;
  // global signal glbl.vcc3v3;
  // global signal glbl.vcc3v3_iv;
  // global signal glbl.vin3v5_dcdc;
  // global signal glbl.vp12;
  // global signal glbl.vp1v8;
  // global signal glbl.vp1v8_iv;
  // global signal glbl.vp3v3;
  // global signal glbl.vp3v3_iv;
  // global signal glbl.vp3v5;

  wire  dcdc_enable;
  wire  dcdc_pg;
  wire  n000130;
  wire  n000231;
  wire  n000312;
  wire  n00167;
  wire  n00175;
  wire  n00181;
  wire  n003941;
  wire  n003961;
  wire  n004041;
  wire  n004340;
  wire  n00860;
  wire  n00870;
  wire  n00872;
  wire  n00876;
  wire  n00880;
  wire  n00884;
  wire  n00888;
  wire  n00890;
  wire  n00894;
  wire  n00902;
  wire  n00904;
  wire  n00912;
  wire  \power.pg_vcc3v3 ;
  wire  \power.pg_vp1v8 ;
  wire  \power.pg_vp3v3 ;
  wire  \power.sense_12c_scl ;
  wire  \power.sense_12c_sda ;
  wire  sns1;
  wire  sns3;
  wire  util_pwr_en;
  wire  vout3v3b;
  wire  vp12_en;

  wire  page2_fpga_pg;
  wire  gnd;
  wire  page2_gnd;
  wire  page1_gnd;
  wire  mp3v3;
  wire  page1_mp3v3;
  wire [10:0] page2_power;
  wire  vcc3v3;
  wire  page2_vcc3v3;
  wire  vcc3v3_iv;
  wire  page2_vcc3v3_iv;
  wire  vin3v5_dcdc;
  wire  page1_vin3v5_dcdc;
  wire  page2_vout3v3b;
  wire  vp12;
  wire  page2_vp12;
  wire  page1_vp12;
  wire  vp1v8;
  wire  page2_vp1v8;
  wire  vp1v8_iv;
  wire  page2_vp1v8_iv;
  wire  vp3v3;
  wire  page2_vp3v3;
  wire  vp3v3_iv;
  wire  page2_vp3v3_iv;
  wire  vp3v5;
  wire  page2_vp3v5;
  wire  page1_vp3v5;

  assign page2_fpga_pg = fpga_pg;
  assign gnd = glbl.gnd;
  assign page2_gnd = gnd;
  assign page1_gnd = gnd;
  assign mp3v3 = glbl.mp3v3;
  assign page1_mp3v3 = mp3v3;
  assign page2_power[10:0] = power[10:0];
  assign page2_power[10:0] = power[10:0];
  assign page2_power[10:0] = power[10:0];
  assign vcc3v3 = glbl.vcc3v3;
  assign page2_vcc3v3 = vcc3v3;
  assign vcc3v3_iv = glbl.vcc3v3_iv;
  assign page2_vcc3v3_iv = vcc3v3_iv;
  assign vin3v5_dcdc = glbl.vin3v5_dcdc;
  assign page1_vin3v5_dcdc = vin3v5_dcdc;
  assign page2_vout3v3b = vout3v3b;
  assign vp12 = glbl.vp12;
  assign page2_vp12 = vp12;
  assign page1_vp12 = vp12;
  assign vp1v8 = glbl.vp1v8;
  assign page2_vp1v8 = vp1v8;
  assign vp1v8_iv = glbl.vp1v8_iv;
  assign page2_vp1v8_iv = vp1v8_iv;
  assign vp3v3 = glbl.vp3v3;
  assign page2_vp3v3 = vp3v3;
  assign vp3v3_iv = glbl.vp3v3_iv;
  assign page2_vp3v3_iv = vp3v3_iv;
  assign vp3v5 = glbl.vp3v5;
  assign page2_vp3v5 = vp3v5;
  assign page1_vp3v5 = vp3v5;

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign vp12  = glbl.vp12;
  assign vp3v5  = glbl.vp3v5;
  assign mp3v3  = glbl.mp3v3;
  assign vin3v5_dcdc  = glbl.vin3v5_dcdc;
  assign vp3v5  = glbl.vp3v5;
  assign vp12  = glbl.vp12;
  assign gnd  = glbl.gnd;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign vcc3v3  = glbl.vcc3v3;
  assign \power.sense_12c_scl   = power[2];
  assign vcc3v3  = glbl.vcc3v3;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign vp12  = glbl.vp12;
  assign vp1v8_iv  = glbl.vp1v8_iv;
  assign vp1v8  = glbl.vp1v8;
  assign vout3v3b  = glbl.vcc3v3_iv;
  assign vp3v5  = glbl.vp3v5;
  assign vp3v3_iv  = glbl.vp3v3_iv;
  assign vp3v3  = glbl.vp3v3;
  assign vp3v5  = glbl.vp3v5;
  assign vp12  = glbl.vp12;
  assign vp3v3  = glbl.vp3v3;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign vp12  = glbl.vp12;
  assign gnd  = glbl.gnd;
  assign vp3v3  = glbl.vp3v3;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign vp3v5  = glbl.vp3v5;
  assign \power.sense_12c_sda   = power[3];

// begin instances 

  cap_pol page1_105p  (.\1 (glbl.vin3v5_dcdc),
	.\2 (glbl.gnd));

  r page1_106p  (.\1 (vp12_en),
	.\2 (glbl.gnd));

  cap_np page1_107p  (.\1 (n00167),
	.\2 (glbl.gnd));

  r page1_108p  (.\1 (glbl.vp3v5),
	.\2 (dcdc_pg));

  r page1_109p  (.\1 (n00175),
	.\2 (glbl.vin3v5_dcdc));

  uws_series page1_110p  (.\+sense (glbl.vin3v5_dcdc),
	.\+vin (vp12),
	.\+vout (glbl.vin3v5_dcdc),
	.\-sense (glbl.gnd),
	.\-vin (glbl.gnd),
	.\-vout (glbl.gnd),
	.\on/off_ctrl (vp12_en),
	.output_trim(n00175));

  r page1_111p  (.\1 (n000130),
	.\2 (glbl.vp3v5));

  cap_pol page1_112p  (.\1 (glbl.vp3v5),
	.\2 (glbl.gnd));

  r page1_113p  (.\1 (glbl.vin3v5_dcdc),
	.\2 (glbl.vp3v5));

  cap_np page1_115p  (.\1 (vp12),
	.\2 (glbl.gnd));

  r page1_116p  (.\1 (glbl.gnd),
	.\2 (n000231));

  r page1_117p  (.\1 (dcdc_pg),
	.\2 (glbl.gnd));

  cap_np page1_118p  (.\1 (glbl.vin3v5_dcdc),
	.\2 (glbl.gnd));

  cap_np page1_119p  (.\1 (glbl.vin3v5_dcdc),
	.\2 (glbl.gnd));

  ltc2945cud page1_120p  (.adin(glbl.gnd),
	.adr0(n000312),
	.adr1(n000231),
	.alert(/* unconnected */),
	.gnd(glbl.gnd),
	.intvcc(n00167),
	.pad(glbl.gnd),
	.scl(\power.sense_12c_scl ),
	.sdai(\power.sense_12c_sda ),
	.sdao(\power.sense_12c_sda ),
	.\sense+ (glbl.vin3v5_dcdc),
	.\sense- (glbl.vp3v5),
	.vdd(vp12));

  \led#20red#200603_0  page1_121p  (.a(n000130),
	.k(glbl.gnd));

  r page1_122p  (.\1 (glbl.mp3v3),
	.\2 (n00181));

  testpoint page1_123p  (.tp(glbl.vp3v5));

  cap_np page1_124p  (.\1 (vp12),
	.\2 (glbl.gnd));

  r page1_125p  (.\1 (n00167),
	.\2 (n000312));

  cap_np_0 page1_126p  (.\1 (vp12),
	.\2 (glbl.gnd));

  hdr1x3 page1_127p  (.p1(n00181),
	.p2(vp12_en),
	.p3(dcdc_enable));

  r page1_128p  (.\1 (n00175),
	.\2 (glbl.gnd));

  cap_np page1_129p  (.\1 (vp12),
	.\2 (glbl.gnd));

  testpoint page1_130p  (.tp(glbl.gnd));

  ltc2945cud page2_133p  (.adin(glbl.gnd),
	.adr0(n00870),
	.adr1(n004041),
	.alert(/* unconnected */),
	.gnd(glbl.gnd),
	.intvcc(n00860),
	.pad(glbl.gnd),
	.scl(\power.sense_12c_scl ),
	.sdai(\power.sense_12c_sda ),
	.sdao(\power.sense_12c_sda ),
	.\sense+ (glbl.vp3v3_iv),
	.\sense- (vp3v3),
	.vdd(glbl.vp12));

  cap_np page2_134p  (.\1 (glbl.vp1v8_iv),
	.\2 (glbl.gnd));

  testpoint page2_135p  (.tp(vp3v3));

  testpoint page2_136p  (.tp(glbl.vp1v8_iv));

  testpoint page2_137p  (.tp(glbl.vp3v3_iv));

  r page2_138p  (.\1 (glbl.vp1v8),
	.\2 (n00904));

  cap_np page2_139p  (.\1 (vp3v3),
	.\2 (glbl.gnd));

  testpoint page2_140p  (.tp(glbl.gnd));

  cap_np page2_141p  (.\1 (sns3),
	.\2 (n00894));

  cap_np_0 page2_142p  (.\1 (glbl.vp12),
	.\2 (glbl.gnd));

  cap_np page2_143p  (.\1 (n00880),
	.\2 (glbl.gnd));

  cap_np page2_144p  (.\1 (glbl.vp1v8),
	.\2 (glbl.gnd));

  r page2_145p  (.\1 (vcc3v3),
	.\2 (\power.pg_vp1v8 ));

  testpoint page2_146p  (.tp(vcc3v3));

  cap_np page2_147p  (.\1 (n00890),
	.\2 (glbl.gnd));

  r page2_148p  (.\1 (vp3v3),
	.\2 (\power.pg_vcc3v3 ));

  cap_np page2_149p  (.\1 (vcc3v3),
	.\2 (glbl.gnd));

  r page2_150p  (.\1 (glbl.vp1v8_iv),
	.\2 (glbl.vp1v8));

  ltc2945cud page2_151p  (.adin(glbl.gnd),
	.adr0(/* unconnected */),
	.adr1(/* unconnected */),
	.alert(/* unconnected */),
	.gnd(glbl.gnd),
	.intvcc(n00880),
	.pad(glbl.gnd),
	.scl(\power.sense_12c_scl ),
	.sdai(\power.sense_12c_sda ),
	.sdao(\power.sense_12c_sda ),
	.\sense+ (vout3v3b),
	.\sense- (vcc3v3),
	.vdd(glbl.vp12));

  cap_np page2_152p  (.\1 (glbl.vp3v3_iv),
	.\2 (glbl.gnd));

  cap_np page2_153p  (.\1 (vp3v3),
	.\2 (glbl.gnd));

  r page2_154p  (.\1 (vp3v3),
	.\2 (\power.pg_vp3v3 ));

  testpoint page2_155p  (.tp(glbl.gnd));

  cap_np page2_156p  (.\1 (vcc3v3),
	.\2 (glbl.gnd));

  r page2_157p  (.\1 (n004340),
	.\2 (vcc3v3));

  cap_np page2_158p  (.\1 (n00860),
	.\2 (glbl.gnd));

  tps74618p page2_159p  (.en(util_pwr_en),
	.epad(glbl.gnd),
	.gnd(glbl.gnd),
	.in(vcc3v3),
	.out(glbl.vp1v8_iv),
	.pg(\power.pg_vp1v8 ));

  cap_np page2_160p  (.\1 (n00872),
	.\2 (glbl.gnd));

  cap_np page2_161p  (.\1 (glbl.vp3v5),
	.\2 (glbl.gnd));

  cap_np_0 page2_162p  (.\1 (glbl.vp12),
	.\2 (glbl.gnd));

  testpoint page2_163p  (.tp(glbl.gnd));

  r page2_164p  (.\1 (glbl.vp3v3_iv),
	.\2 (vp3v3));

  cap_np page2_165p  (.\1 (vout3v3b),
	.\2 (glbl.gnd));

  cap_np page2_166p  (.\1 (glbl.vp3v5),
	.\2 (glbl.gnd));

  testpoint page2_167p  (.tp(vout3v3b));

  r page2_168p  (.\1 (n00904),
	.\2 (glbl.gnd));

  r page2_169p  (.\1 (n00860),
	.\2 (n004041));

  cap_np_0 page2_171p  (.\1 (glbl.vp12),
	.\2 (glbl.gnd));

  cap_np page2_172p  (.\1 (n00884),
	.\2 (glbl.gnd));

  cap_np page2_173p  (.\1 (glbl.vp3v5),
	.\2 (glbl.gnd));

  testpoint page2_174p  (.tp(glbl.vp1v8));

  cap_np page2_175p  (.\1 (glbl.vp3v3_iv),
	.\2 (glbl.gnd));

  cap_np page2_176p  (.\1 (vcc3v3),
	.\2 (glbl.gnd));

  ltc2945cud page2_177p  (.adin(glbl.gnd),
	.adr0(n00888),
	.adr1(/* unconnected */),
	.alert(/* unconnected */),
	.gnd(glbl.gnd),
	.intvcc(n00884),
	.pad(glbl.gnd),
	.scl(\power.sense_12c_scl ),
	.sdai(\power.sense_12c_sda ),
	.sdao(\power.sense_12c_sda ),
	.\sense+ (glbl.vp1v8_iv),
	.\sense- (glbl.vp1v8),
	.vdd(glbl.vp12));

  cap_np page2_178p  (.\1 (sns1),
	.\2 (n00876));

  r page2_179p  (.\1 (sns3),
	.\2 (vcc3v3));

  cap_np page2_180p  (.\1 (glbl.vp1v8),
	.\2 (glbl.gnd));

  cap_np page2_181p  (.\1 (glbl.vp3v5),
	.\2 (glbl.gnd));

  r page2_182p  (.\1 (sns1),
	.\2 (vp3v3));

  cap_np page2_183p  (.\1 (vp3v3),
	.\2 (glbl.gnd));

  r page2_184p  (.\1 (glbl.gnd),
	.\2 (n00888));

  cap_np page2_185p  (.\1 (vp3v3),
	.\2 (glbl.gnd));

  tps7a8500rgrt page2_186p  (.\1.6v (glbl.gnd),
	.\50mv (/* unconnected */),
	.\100mv (glbl.gnd),
	.\200mv (/* unconnected */),
	.\400mv (/* unconnected */),
	.\800mv (glbl.gnd),
	.bias(/* unconnected */),
	.en(util_pwr_en),
	.epad(glbl.gnd),
	.fb(n00894),
	.gnd1(glbl.gnd),
	.gnd2(glbl.gnd),
	.in1(glbl.vp3v5),
	.in2(glbl.vp3v5),
	.in3(glbl.vp3v5),
	.\nr/ss (n00890),
	.out1(vout3v3b),
	.out2(vout3v3b),
	.out3(vout3v3b),
	.pg(\power.pg_vcc3v3 ),
	.sns(sns3));

  bss138 page2_187p  (.d(n00902),
	.g(n00904),
	.s(glbl.gnd));

  \led#20green#200603_0  page2_188p  (.a(n004340),
	.k(glbl.gnd));

  r page2_189p  (.\1 (vout3v3b),
	.\2 (vcc3v3));

  r page2_190p  (.\1 (vcc3v3),
	.\2 (n003941));

  \led#20green#200603_0  page2_191p  (.a(n003941),
	.k(n00902));

  r page2_192p  (.\1 (glbl.gnd),
	.\2 (n00870));

  \led#20green#200603_0  page2_193p  (.a(n003961),
	.k(glbl.gnd));

  cap_np page2_194p  (.\1 (glbl.vp1v8_iv),
	.\2 (glbl.gnd));

  cap_np page2_195p  (.\1 (vcc3v3),
	.\2 (glbl.gnd));

  r page2_196p  (.\1 (n003961),
	.\2 (vp3v3));

  cap_np page2_197p  (.\1 (vout3v3b),
	.\2 (glbl.gnd));

  r page2_198p  (.\1 (glbl.vp3v5),
	.\2 (n00912));

  tps7a8500rgrt page2_199p  (.\1.6v (glbl.gnd),
	.\50mv (/* unconnected */),
	.\100mv (glbl.gnd),
	.\200mv (/* unconnected */),
	.\400mv (/* unconnected */),
	.\800mv (glbl.gnd),
	.bias(/* unconnected */),
	.en(glbl.vp3v5),
	.epad(glbl.gnd),
	.fb(n00876),
	.gnd1(glbl.gnd),
	.gnd2(glbl.gnd),
	.in1(glbl.vp3v5),
	.in2(glbl.vp3v5),
	.in3(glbl.vp3v5),
	.\nr/ss (n00872),
	.out1(glbl.vp3v3_iv),
	.out2(glbl.vp3v3_iv),
	.out3(glbl.vp3v3_iv),
	.pg(\power.pg_vp3v3 ),
	.sns(sns1));

  hdr1x3 page2_200p  (.p1(n00912),
	.p2(util_pwr_en),
	.p3(fpga_pg));

endmodule // \02_#20power (sch_1) 
