-- generated by newgenasym Thu Feb 13 12:50:02 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \shf-105-01-x-d-sm\ is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (9 DOWNTO 0));
end \shf-105-01-x-d-sm\;
