// generated by newgenasym  Mon Apr 17 13:53:43 2023


module tantpoly (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
