-- generated by newgenasym Mon Apr 17 13:53:43 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tantpoly is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end tantpoly;
