`timescale 1ns/1ns

module \01_#20module#20management#20ctrl  (bp, power, fpga_pg );
// generated by  HDL Direct 17.4-2019 S031 (4044358) 7/23/2022
// on Sat Dec 31 17:29:52 2022
// from mtca_interface_board_reocc/01_ MODULE MANAGEMENT CTRL/sch_1

  inout [180:0] bp;
  inout [10:0] power;
  input  fpga_pg;
  // global signal glbl.gnd;
  // global signal glbl.mp3v3;
  // global signal glbl.vp12;

  wire  blue_led;
  wire  \bp.amc_ga0 ;
  wire  \bp.amc_ga1 ;
  wire  \bp.amc_ga2 ;
  wire  \bp.amc_ipmb_scl ;
  wire  \bp.amc_ipmb_sda ;
  wire  \bp.amc_n-enable ;
  wire  \bp.amc_n-ps0 ;
  wire  \bp.amc_n-ps1 ;
  wire  \bp.pwr_on ;
  wire  \bp.tck ;
  wire  \bp.tdi ;
  wire  \bp.tdo ;
  wire  \bp.tms ;
  wire  green_led;
  wire  handle_sw_close_n;
  wire  n00455;
  wire  n00469;
  wire  n00471;
  wire  n00473;
  wire  n00481;
  wire  n00497;
  wire  n00503;
  wire  n00505;
  wire  n00507;
  wire  nover_temp;
  wire  \power.dcdc_enable ;
  wire  \power.dcdc_pg ;
  wire  \power.pg_vcc3v3 ;
  wire  \power.pg_vccio ;
  wire  \power.pg_vp1v8 ;
  wire  \power.pg_vp3v3 ;
  wire  \power.sense_12c_scl ;
  wire  \power.sense_12c_sda ;
  wire  \power.vcc3v3_en ;
  wire  \power.vccio_en ;
  wire  \power.vp1v8_en ;
  wire  presence_12v;
  wire  red_led;
  wire  reset;
  wire  rtm_ps;
  wire  tck;
  wire  tdi;
  wire  tdo;
  wire  tms;
  wire [2:0] \bp.amc_ga ;
  wire [1:0] \bp.amc_n-ps ;

  wire [180:0] page1_bp;
  wire  page1_fpga_pg;
  wire  gnd;
  wire  page1_gnd;
  wire  mp3v3;
  wire  page1_mp3v3;
  wire [10:0] page1_power;
  wire  vp12;
  wire  page1_vp12;

  assign page1_bp[180:0] = bp[180:0];
  assign page1_bp[180:0] = bp[180:0];
  assign page1_fpga_pg = fpga_pg;
  assign gnd = glbl.gnd;
  assign page1_gnd = gnd;
  assign mp3v3 = glbl.mp3v3;
  assign page1_mp3v3 = mp3v3;
  assign page1_power[10:0] = power[10:0];
  assign page1_power[10:0] = power[10:0];
  assign page1_power[10:0] = power[10:0];
  assign vp12 = glbl.vp12;
  assign page1_vp12 = vp12;

  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign vp12  = glbl.vp12;
  assign mp3v3  = glbl.mp3v3;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign gnd  = glbl.gnd;
  assign mp3v3  = glbl.mp3v3;
  assign mp3v3  = glbl.mp3v3;
  assign mp3v3  = glbl.mp3v3;
  assign mp3v3  = glbl.mp3v3;
  assign mp3v3  = glbl.mp3v3;

// begin instances 

  r page1_162p  (.\1 (glbl.mp3v3),
	.\2 (tdo));

  lm75a page1_163p  (.\+vs (glbl.mp3v3),
	.a0(glbl.gnd),
	.a1(glbl.gnd),
	.a2(glbl.gnd),
	.gnd(glbl.gnd),
	.os(nover_temp),
	.scl(\power.sense_12c_scl ),
	.sda(\power.sense_12c_sda ));

  r page1_164p  (.\1 (glbl.mp3v3),
	.\2 (\power.sense_12c_scl ));

  \led#20green#200603_0  page1_165p  (.a(glbl.mp3v3),
	.k(n00505));

  cap_np page1_166p  (.\1 (n00455),
	.\2 (glbl.gnd));

  r page1_167p  (.\1 (glbl.mp3v3),
	.\2 (handle_sw_close_n));

  r page1_168p  (.\1 (glbl.gnd),
	.\2 (presence_12v));

  r page1_169p  (.\1 (n00473),
	.\2 (glbl.gnd));

  r page1_170p  (.\1 (glbl.mp3v3),
	.\2 (n00473));

  inv_1ch_od page1_171p  (.a(\bp.amc_n-enable ),
	.gnd(glbl.gnd),
	.nc(/* unconnected */),
	.vcc(glbl.mp3v3),
	.y(reset));

  r page1_172p  (.\1 (glbl.mp3v3),
	.\2 (\power.sense_12c_sda ));

  \led#20red#200603_0  page1_173p  (.a(glbl.mp3v3),
	.k(n00507));

  r page1_174p  (.\1 (n00471),
	.\2 (\power.sense_12c_scl ));

  r page1_175p  (.\1 (glbl.mp3v3),
	.\2 (tms));

  hdt0001 page1_176p  (.a(glbl.gnd),
	.b(handle_sw_close_n),
	.c(glbl.gnd),
	.d(handle_sw_close_n));

  diode page1_177p  (.anode(n00497),
	.cathode(\bp.amc_n-ps0 ));

  led_0 page1_178p  (.\1 (n00503),
	.\2 (glbl.mp3v3));

  cap_np page1_179p  (.\1 (glbl.mp3v3),
	.\2 (glbl.gnd));

  r page1_180p  (.\1 (glbl.mp3v3),
	.\2 (rtm_ps));

  \recpt#205x2#20100mil  page1_181p  (.\1 (tck),
	.\2 (glbl.gnd),
	.\3 (tdo),
	.\4 (glbl.mp3v3),
	.\5 (tms),
	.\6 (/* unconnected */),
	.\7 (/* unconnected */),
	.\8 (/* unconnected */),
	.\9 (tdi),
	.\10 (glbl.gnd));

  r page1_182p  (.\1 (n00481),
	.\2 (\bp.amc_ga2 ));

  r page1_183p  (.\1 (n00505),
	.\2 (green_led));

  r page1_184p  (.\1 (glbl.mp3v3),
	.\2 (reset));

  r page1_185p  (.\1 (glbl.mp3v3),
	.\2 (tdi));

  r page1_186p  (.\1 (glbl.mp3v3),
	.\2 (\bp.amc_ipmb_scl ));

  r page1_187p  (.\1 (presence_12v),
	.\2 (glbl.vp12));

  r page1_188p  (.\1 (\bp.amc_n-ps1 ),
	.\2 (n00497));

  r page1_189p  (.\1 (n00481),
	.\2 (\bp.amc_ga1 ));

  r page1_190p  (.\1 (n00507),
	.\2 (red_led));

  r page1_191p  (.\1 (glbl.mp3v3),
	.\2 (tck));

  r page1_192p  (.\1 (n00473),
	.\2 (\bp.amc_n-ps0 ));

  r page1_193p  (.\1 (glbl.mp3v3),
	.\2 (\bp.amc_n-enable ));

  ind page1_194p  (.\1 (n00455),
	.\2 (glbl.mp3v3));

  r page1_195p  (.\1 (n00503),
	.\2 (blue_led));

  r page1_196p  (.\1 (glbl.mp3v3),
	.\2 (\bp.amc_ipmb_sda ));

  atmga128 page1_197p  (.aref(n00455),
	.avcc(n00455),
	.epad(glbl.gnd),
	.gnd1(glbl.gnd),
	.gnd2(glbl.gnd),
	.gnd3(glbl.gnd),
	.pa0(\power.dcdc_pg ),
	.pa1(presence_12v),
	.pa2(rtm_ps),
	.pa3(/* unconnected */),
	.pa4(/* unconnected */),
	.pa5(/* unconnected */),
	.pa6(/* unconnected */),
	.pa7(/* unconnected */),
	.pb0(n00481),
	.pb1(\bp.amc_ga0 ),
	.pb2(\bp.amc_ga1 ),
	.pb3(\bp.amc_ga2 ),
	.pb4(/* unconnected */),
	.pb5(red_led),
	.pb6(green_led),
	.pb7(blue_led),
	.pc0(/* unconnected */),
	.pc1(/* unconnected */),
	.pc2(/* unconnected */),
	.pc3(/* unconnected */),
	.pc4(/* unconnected */),
	.pc5(/* unconnected */),
	.pc6(/* unconnected */),
	.pc7(\power.dcdc_enable ),
	.pd0(n00469),
	.pd1(\bp.amc_ipmb_sda ),
	.pd2(handle_sw_close_n),
	.pd3(/* unconnected */),
	.pd4(n00471),
	.pd5(\power.sense_12c_sda ),
	.pd6(/* unconnected */),
	.pd7(/* unconnected */),
	.pe0(nover_temp),
	.pe1(/* unconnected */),
	.pe2(\bp.amc_n-ps1 ),
	.pe3(n00473),
	.pe4(fpga_pg),
	.pe5(\power.pg_vp1v8 ),
	.pe6(\power.pg_vp3v3 ),
	.pe7(\power.pg_vcc3v3 ),
	.\pen* (/* unconnected */),
	.pf0(/* unconnected */),
	.pf1(/* unconnected */),
	.pf2(/* unconnected */),
	.pf3(/* unconnected */),
	.pf4(tck),
	.pf5(tms),
	.pf6(tdo),
	.pf7(tdi),
	.pg0(\bp.tck ),
	.pg1(\bp.tms ),
	.pg2(\bp.tdo ),
	.pg3(\bp.tdi ),
	.pg4(/* unconnected */),
	.\reset* (reset),
	.vcc1(glbl.mp3v3),
	.vcc2(glbl.mp3v3),
	.xtal1(/* unconnected */),
	.xtal2(/* unconnected */));

  cap_np page1_198p  (.\1 (glbl.mp3v3),
	.\2 (glbl.gnd));

  r page1_199p  (.\1 (n00481),
	.\2 (\bp.amc_ga0 ));

  cap_np page1_200p  (.\1 (glbl.mp3v3),
	.\2 (glbl.gnd));

  r page1_201p  (.\1 (\bp.amc_n-ps1 ),
	.\2 (glbl.gnd));

  lp_515xxx page1_202p  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */));

  r page1_203p  (.\1 (n00469),
	.\2 (\bp.amc_ipmb_scl ));

endmodule // \01_#20module#20management#20ctrl (sch_1) 
