-- generated by newgenasym Fri Nov 09 17:39:42 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CON10P is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (9 DOWNTO 0));
end CON10P;
