// generated by newgenasym  Fri Oct 04 17:52:53 2013


module rsmd0603 (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
