-- generated by newgenasym Fri Oct 04 17:52:53 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity RSMD0603 is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end RSMD0603;
