// generated by newgenasym  Wed Mar  8 11:14:59 2023


module \01_#20module#20management#20ctrl  (bp, fpga_pg, power);
    inout [180:0] bp;
    input fpga_pg;
    inout [5:0] power;


    initial
        begin
        end

endmodule
