-- generated by newgenasym Wed Mar  8 11:14:59 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \01_ module management ctrl\ is
    port (    
	BP:        INOUT  std_logic_vector (180 DOWNTO 0);    
	FPGA_PG:   IN     std_logic;    
	POWER:     INOUT  std_logic_vector (5 DOWNTO 0));
end \01_ module management ctrl\;
