-- generated by newgenasym Mon Jun 25 09:50:36 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ELCAPTAN is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end ELCAPTAN;
