// generated by newgenasym  Thu Jul  3 10:38:57 2003


module kkcon3 (a1, a2, b1);
    parameter    size = 1;
    inout [size-1:0] a1;
    inout [size-1:0] a2;
    inout [size-1:0] b1;


    initial
        begin
        end

endmodule
