-- generated by newgenasym Mon Feb 24 12:27:05 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity wurth_smsw is
    port (    
	A:         INOUT  STD_LOGIC;    
	\wurth smsw\: INOUT  STD_LOGIC);
end wurth_smsw;
