// generated by newgenasym  Tue Apr 01 16:07:26 2014


module optocoupler_ac_ec (anode, cathode, collector, emitter);
    inout anode;
    inout cathode;
    inout collector;
    inout emitter;


    initial
        begin
        end

endmodule
