-- generated by newgenasym Tue Apr 01 16:07:26 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity optocoupler_ac_ec is
    port (    
	ANODE:     INOUT  STD_LOGIC;    
	CATHODE:   INOUT  STD_LOGIC;    
	COLLECTOR: INOUT  STD_LOGIC;    
	EMITTER:   INOUT  STD_LOGIC);
end optocoupler_ac_ec;
