// generated by newgenasym  Tue Oct  6 17:18:39 2026


module \sw#20dpdt  (common1, common2, nc1, nc2, no1, no2);
    inout common1;
    inout common2;
    inout nc1;
    inout nc2;
    inout no1;
    inout no2;


    initial
        begin
        end

endmodule
