// generated by newgenasym  Sun Jan  1 17:14:35 2023


module \04_#20sfp_module  (los, rate_select, rd_n, rd_p, scl, sda, td_n, td_p,
        tx_disable, tx_fault);
    output los;
    input rate_select;
    output rd_n;
    output rd_p;
    input scl;
    inout sda;
    input td_n;
    input td_p;
    input tx_disable;
    output tx_fault;


    initial
        begin
        end

endmodule
