-- generated by newgenasym Sun Jan  1 17:14:35 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \04_ sfp_module\ is
    port (    
	LOS:       OUT    STD_LOGIC;    
	RATE_SELECT: IN     STD_LOGIC;    
	RD_N:      OUT    STD_LOGIC;    
	RD_P:      OUT    STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	TD_N:      IN     STD_LOGIC;    
	TD_P:      IN     STD_LOGIC;    
	TX_DISABLE: IN     STD_LOGIC;    
	TX_FAULT:  OUT    STD_LOGIC);
end \04_ sfp_module\;
