// generated by newgenasym  Fri May 25 18:22:12 2012


module rsmd0402 (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
