// generated by newgenasym  Sat Dec 31 14:33:52 2022


module uws_series (\+sense , \+vin , \+vout , \-vin , \on/off_ctrl , output_trim,
        \sense* , \vout* );
    input \+sense ;
    input \+vin ;
    output \+vout ;
    input \-vin ;
    input \on/off_ctrl ;
    output output_trim;
    input \sense* ;
    output \vout* ;


    initial
        begin
        end

endmodule
