-- generated by newgenasym Sat Dec 31 14:33:52 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity uws_series is
    port (    
	\+sense\:  IN     STD_LOGIC;    
	\+vin\:    IN     STD_LOGIC;    
	\+vout\:   OUT    STD_LOGIC;    
	\-vin\:    IN     STD_LOGIC;    
	\on/off_ctrl\: IN     STD_LOGIC;    
	OUTPUT_TRIM: OUT    STD_LOGIC;    
	\sense*\:  IN     STD_LOGIC;    
	\vout*\:   OUT    STD_LOGIC);
end uws_series;
