// generated by newgenasym  Fri Oct 17 10:51:21 2014


module ferrite (a, b);
    parameter    size = 1;
    inout [size-1:0] a;
    inout [size-1:0] b;


    initial
        begin
        end

endmodule
