-- generated by newgenasym Fri Oct 17 10:51:21 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity FERRITE is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end FERRITE;
