-- generated by newgenasym Fri Sep 27 17:52:25 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity CON3P is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (2 DOWNTO 0));
end CON3P;
