// generated by newgenasym  Tue Jul 10 10:19:34 2012


module sy58608u (in, \in* , q0, \q0* , q1, \q1* , \vref-ac , vt);
    input in;
    input \in* ;
    output q0;
    output \q0* ;
    output q1;
    output \q1* ;
    output \vref-ac ;
    input vt;


    initial
        begin
        end

endmodule
