// generated by newgenasym  Tue Jan 08 15:15:38 2013


module osc_6p_endis_outp_outn (endis, outn, outp);
    input endis;
    output outn;
    output outp;


    initial
        begin
        end

endmodule
