-- generated by newgenasym Tue Jan 08 15:15:38 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity OSC_6P_ENDIS_OUTP_OUTN is
    port (    
	ENDIS:     IN     STD_LOGIC;    
	OUTN:      OUT    STD_LOGIC;    
	OUTP:      OUT    STD_LOGIC);
end OSC_6P_ENDIS_OUTP_OUTN;
